In [1]:
import pandas as pd
import io
from datetime import datetime, timedelta

In [2]:
# Load check-in records
df = pd.read_csv('FSQ_SG_2013_Checkins.csv', header=None,
                 names=["user_id", "poi_id", "utc_time", "tz_offset"])

# Load POI ID to (lat, lon) mapping
poi_coords = pd.read_csv('FSQ_SG_2013_POI.csv', header=None, 
                         names=["poi_id", "poi_name", "lat", "lon", "cat_name", "country_code"])

In [3]:
# Apply 5-core filtering
def five_core_filter(df, user_col='user_id', item_col='poi_id', min_interactions=5):
    while True:
        user_counts = df[user_col].value_counts()
        item_counts = df[item_col].value_counts()

        valid_users = user_counts[user_counts >= min_interactions].index
        valid_items = item_counts[item_counts >= min_interactions].index

        df_filtered = df[df[user_col].isin(valid_users) & df[item_col].isin(valid_items)]

        if len(df_filtered) == len(df):
            break
        df = df_filtered

    return df_filtered

df_5core = five_core_filter(df)

#  Filter POI metadata to match filtered POIs
filtered_pois = df_5core['poi_id'].unique()
poi_coords_filtered = poi_coords[poi_coords['poi_id'].isin(filtered_pois)]

len(df_5core), len(poi_coords_filtered)

(308825, 9756)

In [4]:
poi_dict = {}
for idx, row in poi_coords_filtered.iterrows():
    poi_dict[row['poi_id']] = {'name': row['poi_name'], 'lat': row['lat'], 'lon':row['lon'], 'cat': row['cat_name']}

len(poi_dict), poi_dict

(9756,
 {'4a5eb95bf964a52019bf1fe3': {'name': 'Lucasfilm Animation Singapore',
   'lat': 1.335005,
   'lon': 103.964682,
   'cat': 'Office'},
  '4a73e804f964a52099dd1fe3': {'name': 'Buddha Tooth Relic Temple & Museum',
   'lat': 1.281391,
   'lon': 103.844348,
   'cat': 'Temple'},
  '4ac7f7f1f964a520e9ba20e3': {'name': 'New Majestic Hotel',
   'lat': 1.279386,
   'lon': 103.840514,
   'cat': 'Hotel'},
  '4ac8148ff964a5208bbb20e3': {'name': 'Sri Mariamman Temple',
   'lat': 1.282644,
   'lon': 103.845286,
   'cat': 'Temple'},
  '4afa194af964a520b71622e3': {'name': 'Clarke Quay Central',
   'lat': 1.28897,
   'lon': 103.846958,
   'cat': 'Mall'},
  '4b05880af964a5208aad22e3': {'name': 'Carlton Hotel',
   'lat': 1.295568,
   'lon': 103.852641,
   'cat': 'Hotel'},
  '4b05880af964a52092ad22e3': {'name': 'Hotel Grand Central',
   'lat': 1.301201,
   'lon': 103.841561,
   'cat': 'Hotel'},
  '4b05880af964a52093ad22e3': {'name': 'Hotel Miramar',
   'lat': 1.288553,
   'lon': 103.837152,
   'cat': 'Hotel'},
  '4b05880af964a52094ad22e3': {'name': 'Hotel Royal',
   'lat': 1.317065,
   'lon': 103.841629,
   'cat': 'Hotel'},
  '4b05880af964a52097ad22e3': {'name': 'Hilton Singapore Orchard',
   'lat': 1.302369,
   'lon': 103.836164,
   'cat': 'Hotel'},
  '4b05880af964a5209aad22e3': {'name': 'Orchard Rendezvous Hotel',
   'lat': 1.306909,
   'lon': 103.827788,
   'cat': 'Hotel'},
  '4b05880af964a5209ead22e3': {'name': 'RELC International Hotel',
   'lat': 1.312886,
   'lon': 103.825948,
   'cat': 'Hotel'},
  '4b05880af964a520a0ad22e3': {'name': 'Quality Hotel Marlow',
   'lat': 1.319991,
   'lon': 103.852526,
   'cat': 'Hotel'},
  '4b05880af964a520a2ad22e3': {'name': 'Bayview Hotel',
   'lat': 1.298523,
   'lon': 103.850138,
   'cat': 'Hotel'},
  '4b05880af964a520a6ad22e3': {'name': 'M Hotel Singapore',
   'lat': 1.273687,
   'lon': 103.845069,
   'cat': 'Hotel'},
  '4b05880af964a520a7ad22e3': {'name': "Copthorne King's Hotel",
   'lat': 1.288628,
   'lon': 103.836572,
   'cat': 'Hotel'},
  '4b05880af964a520a9ad22e3': {'name': 'Peninsula Excelsior Hotel',
   'lat': 1.292064,
   'lon': 103.850172,
   'cat': 'Hotel'},
  '4b05880af964a520acad22e3': {'name': 'InterContinental Singapore',
   'lat': 1.29812,
   'lon': 103.855013,
   'cat': 'Hotel'},
  '4b05880af964a520adad22e3': {'name': 'Novotel Singapore Clarke Quay',
   'lat': 1.291378,
   'lon': 103.845071,
   'cat': 'Hotel'},
  '4b05880af964a520aead22e3': {'name': 'Rendezvous Hotel Singapore',
   'lat': 1.298304,
   'lon': 103.849345,
   'cat': 'Hotel'},
  '4b05880af964a520afad22e3': {'name': 'Paradox Singapore Merchant Court at Clarke Quay',
   'lat': 1.288833,
   'lon': 103.84596,
   'cat': 'Hotel'},
  '4b05880af964a520b0ad22e3': {'name': 'PARKROYAL on Kitchener Road',
   'lat': 1.310644,
   'lon': 103.855766,
   'cat': 'Hotel'},
  '4b05880bf964a52000ae22e3': {'name': 'Que Pasa Wine & Tapas',
   'lat': 1.301838,
   'lon': 103.839098,
   'cat': 'Wine Bar'},
  '4b05880bf964a52004ae22e3': {'name': 'Ice Cold Beer',
   'lat': 1.301884,
   'lon': 103.839104,
   'cat': 'Bar'},
  '4b05880bf964a520b3ad22e3': {'name': 'Gateway Hotel',
   'lat': 1.3147,
   'lon': 103.898146,
   'cat': 'Hotel'},
  '4b05880bf964a520b6ad22e3': {'name': 'Amara Singapore Hotel',
   'lat': 1.274974,
   'lon': 103.843567,
   'cat': 'Hotel'},
  '4b05880bf964a520b7ad22e3': {'name': 'Orchard Hotel Singapore',
   'lat': 1.307516,
   'lon': 103.827931,
   'cat': 'Hotel'},
  '4b05880bf964a520b9ad22e3': {'name': 'Hotel Jen Tanglin Singapore',
   'lat': 1.303835,
   'lon': 103.823831,
   'cat': 'Hotel'},
  '4b05880bf964a520baad22e3': {'name': 'York Hotel',
   'lat': 1.307077,
   'lon': 103.835531,
   'cat': 'Hotel'},
  '4b05880bf964a520bbad22e3': {'name': 'PARKROYAL on Beach Road',
   'lat': 1.300151,
   'lon': 103.860437,
   'cat': 'Hotel'},
  '4b05880bf964a520bfad22e3': {'name': 'Raffles Hotel',
   'lat': 1.294724,
   'lon': 103.853977,
   'cat': 'Hotel'},
  '4b05880bf964a520c0ad22e3': {'name': 'Royal Plaza On Scotts',
   'lat': 1.306766,
   'lon': 103.832345,
   'cat': 'Hotel'},
  '4b05880bf964a520c1ad22e3': {'name': 'Sheraton Towers Singapore',
   'lat': 1.311657,
   'lon': 103.836679,
   'cat': 'Hotel'},
  '4b05880bf964a520c2ad22e3': {'name': 'Singapore Marriott Tang Plaza Hotel',
   'lat': 1.305344,
   'lon': 103.832622,
   'cat': 'Hotel'},
  '4b05880bf964a520c5ad22e3': {'name': 'Pan Pacific Singapore',
   'lat': 1.291986,
   'lon': 103.858971,
   'cat': 'Hotel'},
  '4b05880bf964a520c6ad22e3': {'name': 'The Ritz-Carlton, Millenia Singapore',
   'lat': 1.290806,
   'lon': 103.86009,
   'cat': 'Hotel'},
  '4b05880bf964a520c7ad22e3': {'name': 'Conrad Centennial Singapore',
   'lat': 1.293339,
   'lon': 103.858818,
   'cat': 'Hotel'},
  '4b05880bf964a520c8ad22e3': {'name': 'Swissôtel The Stamford',
   'lat': 1.293223,
   'lon': 103.853411,
   'cat': 'Hotel'},
  '4b05880bf964a520c9ad22e3': {'name': 'Goodwood Park Hotel',
   'lat': 1.30828,
   'lon': 103.83436,
   'cat': 'Hotel'},
  '4b05880bf964a520caad22e3': {'name': 'South East Asia Hotel',
   'lat': 1.301038,
   'lon': 103.853122,
   'cat': 'Hotel'},
  '4b05880bf964a520ccad22e3': {'name': 'Hotel Supreme (原首酒店)',
   'lat': 1.30134,
   'lon': 103.842399,
   'cat': 'Hotel'},
  '4b05880bf964a520cdad22e3': {'name': 'Pasir Panjang Inn',
   'lat': 1.291936,
   'lon': 103.770185,
   'cat': 'Hotel'},
  '4b05880bf964a520cead22e3': {'name': 'Concorde Hotel',
   'lat': 1.30069,
   'lon': 103.842235,
   'cat': 'Hotel'},
  '4b05880bf964a520cfad22e3': {'name': "Shangri-La's Rasa Sentosa Resort & Spa",
   'lat': 1.257147,
   'lon': 103.810029,
   'cat': 'Resort'},
  '4b05880bf964a520d0ad22e3': {'name': 'Four Seasons Hotel Singapore',
   'lat': 1.304642,
   'lon': 103.828568,
   'cat': 'Hotel'},
  '4b05880bf964a520d1ad22e3': {'name': 'Grand Hyatt Singapore',
   'lat': 1.306353,
   'lon': 103.833297,
   'cat': 'Hotel'},
  '4b05880bf964a520d2ad22e3': {'name': 'Grand Copthorne Waterfront Hotel',
   'lat': 1.290497,
   'lon': 103.835232,
   'cat': 'Hotel'},
  '4b05880bf964a520d4ad22e3': {'name': nan,
   'lat': 1.311626,
   'lon': 103.88085,
   'cat': 'Hotel'},
  '4b05880bf964a520daad22e3': {'name': 'Hotel 81 - Palace',
   'lat': 1.311911,
   'lon': 103.880324,
   'cat': 'Hotel'},
  '4b05880bf964a520dead22e3': {'name': 'YMCA International House',
   'lat': 1.297813,
   'lon': 103.847896,
   'cat': 'Hotel'},
  '4b05880bf964a520dfad22e3': {'name': 'YWCA Fort Canning Lodge',
   'lat': 1.297408,
   'lon': 103.845105,
   'cat': 'Hotel'},
  '4b05880bf964a520e4ad22e3': {'name': 'Victoria Hotel',
   'lat': 1.297078,
   'lon': 103.852505,
   'cat': 'Hotel'},
  '4b05880bf964a520e5ad22e3': {'name': 'Costa Sands Resort (Sentosa)',
   'lat': 1.255161,
   'lon': 103.813959,
   'cat': 'Resort'},
  '4b05880bf964a520e6ad22e3': {'name': 'Aranda Country Club',
   'lat': 1.376194,
   'lon': 103.953809,
   'cat': 'Resort'},
  '4b05880bf964a520e7ad22e3': {'name': 'Shangri-La Hotel',
   'lat': 1.311324,
   'lon': 103.826525,
   'cat': 'Hotel'},
  '4b05880bf964a520e8ad22e3': {'name': 'The Fullerton Hotel',
   'lat': 1.286279,
   'lon': 103.852837,
   'cat': 'Hotel'},
  '4b05880bf964a520eaad22e3': {'name': 'The Scarlet',
   'lat': 1.280542,
   'lon': 103.845422,
   'cat': 'Hotel'},
  '4b05880bf964a520ecad22e3': {'name': 'Holiday Inn Singapore Atrium',
   'lat': 1.289045,
   'lon': 103.834615,
   'cat': 'Hotel'},
  '4b05880bf964a520edad22e3': {'name': 'Hotel Royal @ Queens',
   'lat': 1.297813,
   'lon': 103.852176,
   'cat': 'Hotel'},
  '4b05880bf964a520eead22e3': {'name': 'The St. Regis Singapore',
   'lat': 1.305672,
   'lon': 103.825865,
   'cat': 'Hotel'},
  '4b05880bf964a520efad22e3': {'name': 'Siloso Beach Resort',
   'lat': 1.254469,
   'lon': 103.814633,
   'cat': 'Resort'},
  '4b05880bf964a520f1ad22e3': {'name': 'Big O Gaming Cafe',
   'lat': 1.300502,
   'lon': 103.849832,
   'cat': 'Gaming Cafe'},
  '4b05880bf964a520f3ad22e3': {'name': "Bobby's",
   'lat': 1.295087,
   'lon': 103.852086,
   'cat': 'American Restaurant'},
  '4b05880bf964a520f4ad22e3': {'name': 'Brewerkz Restaurant & Microbrewery',
   'lat': 1.289637,
   'lon': 103.844045,
   'cat': 'Gastropub'},
  '4b05880bf964a520faad22e3': {'name': "Molly Malone's Irish Pub",
   'lat': 1.285995,
   'lon': 103.849442,
   'cat': 'Bar'},
  '4b05880bf964a520fbad22e3': {'name': 'Hard Rock Café Singapore',
   'lat': 1.306184,
   'lon': 103.828082,
   'cat': 'Rock Club'},
  '4b05880bf964a520fdad22e3': {'name': 'The Coffee Bean & Tea Leaf',
   'lat': 1.303162,
   'lon': 103.836229,
   'cat': 'Coffee Shop'},
  '4b05880cf964a5200bae22e3': {'name': 'Paulaner Bräuhaus Singapore',
   'lat': 1.29323,
   'lon': 103.858223,
   'cat': 'Brewery'},
  '4b05880cf964a5200dae22e3': {'name': 'The Penny Black Public House',
   'lat': 1.285829,
   'lon': 103.850069,
   'cat': 'Bar'},
  '4b05880cf964a5200eae22e3': {'name': 'Zouk',
   'lat': 1.291117,
   'lon': 103.834866,
   'cat': 'Nightclub'},
  '4b05880cf964a5201cae22e3': {'name': 'Coffee Club',
   'lat': 1.304637,
   'lon': 103.830832,
   'cat': 'Coffee Shop'},
  '4b05880cf964a5201fae22e3': {'name': 'Billy Bombers Classic',
   'lat': 1.299829,
   'lon': 103.855814,
   'cat': 'Diner'},
  '4b05880cf964a52021ae22e3': {'name': 'Crazy Elephant',
   'lat': 1.289926,
   'lon': 103.846378,
   'cat': 'Pub'},
  '4b05880cf964a52027ae22e3': {'name': 'The Living Room',
   'lat': 1.305522,
   'lon': 103.833032,
   'cat': 'Nightclub'},
  '4b05880cf964a5202eae22e3': {'name': 'New Asia',
   'lat': 1.293452,
   'lon': 103.853439,
   'cat': 'Cocktail Bar'},
  '4b05880cf964a52030ae22e3': {'name': 'Attica',
   'lat': 1.28995,
   'lon': 103.84489,
   'cat': 'Nightclub'},
  '4b05880cf964a52033ae22e3': {'name': 'China One',
   'lat': 1.290227,
   'lon': 103.846174,
   'cat': 'Bar'},
  '4b05880cf964a52035ae22e3': {'name': 'Post Bar',
   'lat': 1.286065,
   'lon': 103.85302,
   'cat': 'Cocktail Bar'},
  '4b05880cf964a52039ae22e3': {'name': 'Velvet Underground',
   'lat': 1.291066,
   'lon': 103.835277,
   'cat': 'Nightclub'},
  '4b05880cf964a52046ae22e3': {'name': 'The Pump Room',
   'lat': 1.290484,
   'lon': 103.845327,
   'cat': 'Rock Club'},
  '4b05880df964a5204aae22e3': {'name': "Samy's Curry",
   'lat': 1.306123,
   'lon': 103.811789,
   'cat': 'Indian Restaurant'},
  '4b05880df964a52057ae22e3': {'name': 'Highlander Bar & Restaurant',
   'lat': 1.29042,
   'lon': 103.845466,
   'cat': 'Bar'},
  '4b05880df964a52058ae22e3': {'name': 'Insomnia',
   'lat': 1.295017,
   'lon': 103.852352,
   'cat': 'Cocktail Bar'},
  '4b05880df964a52064ae22e3': {'name': 'Canvas',
   'lat': 1.28942,
   'lon': 103.848955,
   'cat': 'Nightclub'},
  '4b05880df964a5206aae22e3': {'name': 'PLAY Bar & Club',
   'lat': 1.279636,
   'lon': 103.844227,
   'cat': 'Nightclub'},
  '4b05880df964a5206bae22e3': {'name': 'Rupee Room',
   'lat': 1.290869,
   'lon': 103.845726,
   'cat': 'Nightclub'},
  '4b05880df964a5206fae22e3': {'name': 'Helipad',
   'lat': 1.288838,
   'lon': 103.846639,
   'cat': 'Nightclub'},
  '4b05880df964a5207cae22e3': {'name': 'RedDot BrewHouse',
   'lat': 1.306442,
   'lon': 103.811418,
   'cat': 'Bar'},
  '4b05880df964a5207dae22e3': {'name': "Dorothy's Bar",
   'lat': 1.282967,
   'lon': 103.8441,
   'cat': 'Bar'},
  '4b05880df964a52081ae22e3': {'name': 'Eski Bar',
   'lat': 1.285803,
   'lon': 103.849181,
   'cat': 'Bar'},
  '4b05880df964a52087ae22e3': {'name': 'One Rochester',
   'lat': 1.304946,
   'lon': 103.787851,
   'cat': 'Wine Bar'},
  '4b05880df964a5208aae22e3': {'name': 'The White Rabbit',
   'lat': 1.304852,
   'lon': 103.813557,
   'cat': 'French Restaurant'},
  '4b05880ef964a52093ae22e3': {'name': 'Max Brenner Chocolate Bar',
   'lat': 1.289881,
   'lon': 103.856417,
   'cat': 'Dessert Shop'},
  '4b05880ef964a5209fae22e3': {'name': 'Blu Jaz Cafe',
   'lat': 1.300491,
   'lon': 103.858979,
   'cat': 'Jazz Club'},
  '4b05880ef964a520a1ae22e3': {'name': 'Far East Square',
   'lat': 1.283448,
   'lon': 103.848352,
   'cat': 'Mall'},
  '4b05880ef964a520a3ae22e3': {'name': 'Sun Yat Sen Nanyang Memorial Hall 孙中山南洋纪念馆',
   'lat': 1.327946,
   'lon': 103.847137,
   'cat': 'Monument / Landmark'},
  '4b05880ef964a520adae22e3': {'name': "Sir Stamford Raffles Statue (Raffles' Landing Site)",
   'lat': 1.287722,
   'lon': 103.850691,
   'cat': 'Historic Site'},
  '4b05880ef964a520aeae22e3': {'name': 'Supreme Court',
   'lat': 1.290141,
   'lon': 103.850399,
   'cat': 'Courthouse'},
  '4b05880ef964a520b1ae22e3': {'name': 'Holland Village',
   'lat': 1.311085,
   'lon': 103.795248,
   'cat': 'Other Great Outdoors'},
  '4b05880ef964a520b5ae22e3': {'name': 'Jurong Bird Park',
   'lat': 1.320689,
   'lon': 103.706732,
   'cat': 'Zoo'},
  '4b05880ef964a520bbae22e3': {'name': 'Fort Canning Park',
   'lat': 1.295075,
   'lon': 103.846421,
   'cat': 'Park'},
  '4b05880ef964a520c0ae22e3': {'name': 'Chijmes',
   'lat': 1.295128,
   'lon': 103.85214,
   'cat': 'Art Gallery'},
  '4b05880ef964a520d2ae22e3': {'name': 'Kusu Island',
   'lat': 1.223592,
   'lon': 103.86012,
   'cat': 'Island'},
  '4b05880ef964a520d6ae22e3': {'name': 'Clarke Quay',
   'lat': 1.28984,
   'lon': 103.845005,
   'cat': 'Plaza'},
  '4b05880ef964a520d9ae22e3': {'name': "St Joseph's Catholic Church",
   'lat': 1.29841,
   'lon': 103.85315,
   'cat': 'Church'},
  '4b05880ef964a520dcae22e3': {'name': 'Underwater World And Dolphin Lagoon',
   'lat': 1.258584,
   'lon': 103.811424,
   'cat': 'Aquarium'},
  '4b05880ef964a520e4ae22e3': {'name': 'Thian Hock Keng (Temple)',
   'lat': 1.281028,
   'lon': 103.847664,
   'cat': 'Temple'},
  '4b05880ff964a52002af22e3': {'name': 'Singapore Cricket Club',
   'lat': 1.289217,
   'lon': 103.85229,
   'cat': 'Cricket Ground'},
  '4b05880ff964a52008af22e3': {'name': 'Central Fire Station',
   'lat': 1.292293,
   'lon': 103.849419,
   'cat': 'Fire Station'},
  '4b05880ff964a5200daf22e3': {'name': 'Benjamin Sheares Bridge',
   'lat': 1.294002,
   'lon': 103.865379,
   'cat': 'Bridge'},
  '4b05880ff964a52013af22e3': {'name': nan,
   'lat': 1.324675,
   'lon': 103.930172,
   'cat': 'Other Great Outdoors'},
  '4b05880ff964a52023af22e3': {'name': 'Orchard Road Presbyterian Church (ORPC)',
   'lat': 1.297864,
   'lon': 103.847424,
   'cat': 'Church'},
  '4b05880ff964a52024af22e3': {'name': 'Masjid Omar Kampung Melaka (Mosque)',
   'lat': 1.287888,
   'lon': 103.844141,
   'cat': 'Mosque'},
  '4b05880ff964a5202aaf22e3': {'name': 'Kallang River',
   'lat': 1.308976,
   'lon': 103.870175,
   'cat': 'River'},
  '4b05880ff964a5202caf22e3': {'name': 'Malay Heritage Centre',
   'lat': 1.302626,
   'lon': 103.860133,
   'cat': 'Monument / Landmark'},
  '4b05880ff964a520e6ae22e3': {'name': "St Andrew's Cathedral",
   'lat': 1.292694,
   'lon': 103.852161,
   'cat': 'Church'},
  '4b05880ff964a520e7ae22e3': {'name': 'Cathedral Of The Good Shepherd',
   'lat': 1.29619,
   'lon': 103.851228,
   'cat': 'Church'},
  '4b05880ff964a520e8ae22e3': {'name': 'Central Sikh Gurdwara',
   'lat': 1.31863,
   'lon': 103.860681,
   'cat': 'Temple'},
  '4b05880ff964a520ebae22e3': {'name': 'Arab Street',
   'lat': 1.301202,
   'lon': 103.859198,
   'cat': 'Road'},
  '4b05880ff964a520fbae22e3': {'name': 'Masjid Sultan (Mosque)',
   'lat': 1.3021,
   'lon': 103.859162,
   'cat': 'Mosque'},
  '4b05880ff964a520fcae22e3': {'name': '观音堂佛祖庙 Kwan Im Thong Hood Cho Temple',
   'lat': 1.300872,
   'lon': 103.853003,
   'cat': 'Temple'},
  '4b05880ff964a520fdae22e3': {'name': 'Sri Srinivasa Perumal Temple',
   'lat': 1.313239,
   'lon': 103.856315,
   'cat': 'Monument / Landmark'},
  '4b058810f964a52032af22e3': {'name': nan,
   'lat': 1.284283,
   'lon': 103.853807,
   'cat': 'Monument / Landmark'},
  '4b058810f964a52036af22e3': {'name': 'Esplanade Park',
   'lat': 1.289626,
   'lon': 103.853835,
   'cat': 'Park'},
  '4b058810f964a5203caf22e3': {'name': 'Liang Court',
   'lat': 1.291812,
   'lon': 103.845003,
   'cat': 'Mall'},
  '4b058810f964a5203eaf22e3': {'name': 'Singapore River',
   'lat': 1.287995,
   'lon': 103.84943,
   'cat': 'River'},
  '4b058810f964a52040af22e3': {'name': 'Marina Barrage',
   'lat': 1.280519,
   'lon': 103.870518,
   'cat': 'Water Park'},
  '4b058810f964a52048af22e3': {'name': 'Church Of The Sacred Heart',
   'lat': 1.29619,
   'lon': 103.843854,
   'cat': 'Church'},
  '4b058810f964a52049af22e3': {'name': 'Catholic Church of Our Lady of Lourdes',
   'lat': 1.30315,
   'lon': 103.855998,
   'cat': 'Church'},
  '4b058810f964a5204eaf22e3': {'name': 'Merlion Walk',
   'lat': 1.253008,
   'lon': 103.818572,
   'cat': 'Sculpture Garden'},
  '4b058810f964a5204faf22e3': {'name': 'Church of St Teresa',
   'lat': 1.273322,
   'lon': 103.828053,
   'cat': 'Church'},
  '4b058810f964a52050af22e3': {'name': 'Ministry of Digital Development and Information (MDDI)',
   'lat': 1.290835,
   'lon': 103.848377,
   'cat': 'Government Building'},
  '4b058810f964a52052af22e3': {'name': 'Lee Kong Chian Reference Library',
   'lat': 1.297553,
   'lon': 103.854237,
   'cat': 'Library'},
  '4b058810f964a52054af22e3': {'name': 'The Singapore Flyer',
   'lat': 1.289358,
   'lon': 103.863083,
   'cat': 'Scenic Lookout'},
  '4b058810f964a52059af22e3': {'name': 'Rochester Park',
   'lat': 1.305182,
   'lon': 103.787851,
   'cat': 'Neighborhood'},
  '4b058810f964a52061af22e3': {'name': 'LASALLE College of the Arts',
   'lat': 1.302884,
   'lon': 103.851559,
   'cat': 'College Arts Building'},
  '4b058810f964a52063af22e3': {'name': 'National University of Singapore (NUS)',
   'lat': 1.294088,
   'lon': 103.777714,
   'cat': 'University'},
  '4b058810f964a52064af22e3': {'name': 'Dempsey Hill',
   'lat': 1.304426,
   'lon': 103.810059,
   'cat': 'Neighborhood'},
  '4b058810f964a5206baf22e3': {'name': 'Singapore Discovery Centre',
   'lat': 1.331565,
   'lon': 103.678365,
   'cat': 'Museum'},
  '4b058810f964a5206eaf22e3': {'name': "Children's Museum Singapore",
   'lat': 1.292858,
   'lon': 103.849062,
   'cat': 'Museum'},
  '4b058810f964a5206faf22e3': {'name': 'Singapore Art Museum',
   'lat': 1.297189,
   'lon': 103.850908,
   'cat': 'Art Museum'},
  '4b058810f964a52071af22e3': {'name': 'Asian Civilisations Museum',
   'lat': 1.28688,
   'lon': 103.851978,
   'cat': 'History Museum'},
  '4b058810f964a52072af22e3': {'name': 'Changi Prison Museum & Chapel',
   'lat': 1.362289,
   'lon': 103.973907,
   'cat': 'History Museum'},
  '4b058810f964a52078af22e3': {'name': 'Peranakan Museum',
   'lat': 1.294039,
   'lon': 103.849317,
   'cat': 'History Museum'},
  '4b058811f964a52099af22e3': {'name': 'Chinatown Heritage Centre',
   'lat': 1.283441,
   'lon': 103.844267,
   'cat': 'Museum'},
  '4b058811f964a5209aaf22e3': {'name': 'MINT Museum of Toys',
   'lat': 1.296362,
   'lon': 103.854393,
   'cat': 'Museum'},
  '4b058811f964a5209caf22e3': {'name': "Dan Ryan's Chicago Grill",
   'lat': 1.305366,
   'lon': 103.8252,
   'cat': 'American Restaurant'},
  '4b058811f964a5209faf22e3': {'name': "Tony Roma's",
   'lat': 1.29521,
   'lon': 103.858721,
   'cat': 'American Restaurant'},
  '4b058811f964a520a3af22e3': {'name': 'California Pizza Kitchen',
   'lat': 1.306655,
   'lon': 103.828688,
   'cat': 'Pizza Place'},
  '4b058811f964a520a6af22e3': {'name': "Modesto's",
   'lat': 1.306796,
   'lon': 103.828291,
   'cat': 'Italian Restaurant'},
  '4b058811f964a520a9af22e3': {'name': 'Olive Tree Restaurant',
   'lat': 1.298701,
   'lon': 103.854905,
   'cat': 'Mediterranean Restaurant'},
  '4b058812f964a520b2af22e3': {'name': 'Hua Ting Restaurant 華廳',
   'lat': 1.308058,
   'lon': 103.828144,
   'cat': 'Chinese Restaurant'},
  '4b058812f964a520b8af22e3': {'name': 'Man Fu Yuan',
   'lat': 1.298619,
   'lon': 103.854928,
   'cat': 'Chinese Restaurant'},
  '4b058812f964a520d7af22e3': {'name': 'Ma Maison Restaurant',
   'lat': 1.29923,
   'lon': 103.85606,
   'cat': 'Restaurant'},
  '4b058812f964a520d8af22e3': {'name': 'Fish & Co. (The Glass House)',
   'lat': 1.298089,
   'lon': 103.84493,
   'cat': 'Seafood Restaurant'},
  '4b058812f964a520dbaf22e3': {'name': 'Sofra Turkish Cafe & Restaurant',
   'lat': 1.296596,
   'lon': 103.856349,

In [5]:
# Convert to datetime and apply offset
def parse_local_time(utc_str, offset_min):
    dt = datetime.strptime(utc_str, "%a %b %d %H:%M:%S %z %Y")
    offset = timedelta(minutes=offset_min)
    local_dt = dt + offset
    return local_dt.strftime("%Y-%m-%d %H:%M:%S")

df_5core['local_time'] = df_5core.apply(lambda row: parse_local_time(row['utc_time'], row['tz_offset']), axis=1)

In [6]:
df = df_5core.merge(poi_coords_filtered, on='poi_id', how='left')  # assumes 'lat', 'lon' columns exist
df

,user_id,poi_id,utc_time,tz_offset,local_time,poi_name,lat,lon,cat_name,country_code
0,48739,4cda6665d54954811cdc35b2,Tue Apr 03 18:10:51 +0000 2012,480,2012-04-04 02:10:51,NaN,1.340157,103.920199,Home (private),SG
1,21418,4b138667f964a5208b9723e3,Tue Apr 03 18:19:55 +0000 2012,480,2012-04-04 02:19:55,Xin Wang Hong Kong Café,1.359951,103.884701,Chinese Restaurant,SG
2,49530,4f657a99e4b0c65cc5414938,Tue Apr 03 18:22:10 +0000 2012,480,2012-04-04 02:22:10,Ellyland,1.363290,103.965668,Nightclub,SG
3,224175,4d3b30a336718eec3454748e,Tue Apr 03 18:27:03 +0000 2012,480,2012-04-04 02:27:03,NaN,1.358692,103.955007,Home (private),SG
4,82310,4b1cecc1f964a520800a24e3,Tue Apr 03 18:31:03 +0000 2012,480,2012-04-04 02:31:03,McDonald's,1.312430,103.923304,Fast Food Restaurant,SG
...,...,...,...,...,...,...,...,...,...,...
308820,18277,4b1459aef964a520a7a123e3,Mon Sep 16 23:12:56 +0000 2013,480,2013-09-17 07:12:56,Kovan MRT Station (NE13),1.360305,103.885415,Subway,SG
308821,18277,4c7b131e76ce9c74aa63b50c,Mon Sep 16 23:13:18 +0000 2013,480,2013-09-17 07:13:18,Bus Stop 63039 (Kovan Stn Exit C),1.360326,103.885316,Bus Station,SG
308822,9860,4e7f0cf5f790845961c17293,Mon Sep 16 23:13:57 +0000 2013,480,2013-09-17 07:13:57,Mount Vernon Road,1.342152,103.881066,Field,SG
308823,13358,4d9f5b7d3008dcb3dd23b431,Mon Sep 16 23:20:19 +0000 2013,480,2013-09-17 07:20:19,School of Science and Technology (SST),1.313052,103.773508,High School,SG
308824,9277,4b0c82d7f964a520933e23e3,Mon Sep 16 23:21:31 +0000 2013,480,2013-09-17 07:21:31,Tampines MRT Station (EW2/DT32),1.353094,103.945218,Train Station,SG

In [7]:
# Group and format
def format_checkins(group):
    return '|'.join(f"{row.poi_id},{row.lat},{row.lon},{row.local_time}" for row in group.itertuples())

user_checkins = df.groupby('user_id').apply(format_checkins).reset_index()
user_checkins.columns = ['user_id', 'checkins']

C:\Users\admin\AppData\Local\Temp\ipykernel_46100\468531634.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  user_checkins = df.groupby('user_id').apply(format_checkins).reset_index()

In [8]:
user_checkins.to_csv('./user_checkins.txt', sep='\t', index=False, header=False)

## process the checkin

In [9]:
user_checkins

      user_id                                           checkins
0          16  4e94f6845c5c3201e8ea90f0,1.31079,103.72052,201...
1          51  4ba4c111f964a520f5b138e3,1.30667,103.832735,20...
2          73  4b9096c6f964a5203b9133e3,1.315508,103.8726,201...
3         126  4ca221cf8afca093c12e2116,1.339618,103.983224,2...
4         142  4c6ddd944d24b60cea51d7d8,1.265771,103.860669,2...
...       ...                                                ...
4649   266489  4c0272fcf423a593fac0ce16,1.350936,103.988256,2...
4650   266649  4bb9b8627421a5939df3c240,1.304113,103.833655,2...
4651   266683  4c8e3a94d68c6dcb4059faa1,1.396987,103.910456,2...
4652   266723  4b9f97eff964a520a12d37e3,1.324185,103.930063,2...
4653   266872  4b05880bf964a520b7ad22e3,1.307516,103.827931,2...

[4654 rows x 2 columns]

In [10]:
user_trajs = {}
min_len, max_len = 5, 200

for _, row in user_checkins.iterrows():
    traj_set = []
    user_id = row['user_id']
    checkin_list = row['checkins'].split('|')
    
    if len(checkin_list) < min_len: 
        continue
    elif len(checkin_list) > max_len:
        trajs = [checkin_list[max(i - max_len, 0):i] for i in range(len(checkin_list), 0, -max_len)]
        trajs = trajs[::-1]
        trajs = [t for t in trajs if len(t)>=min_len]
        traj_set.extend(trajs)
    else:
        traj_set.append(checkin_list)

    
    if len(traj_set) > 0:
        user_trajs[user_id] = traj_set

In [11]:
user_checkins['num_checkins'] = user_checkins['checkins'].apply(lambda x: len(str(x).split('|')))
user_checkins = user_checkins.sort_values(by='num_checkins', ascending=False).reset_index(drop=True)

In [12]:
user_checkins.head(20)

    user_id                                           checkins  num_checkins
0        73  4b9096c6f964a5203b9133e3,1.315508,103.8726,201...          2200
1       143  4b1537bbf964a5206ea923e3,1.294471,103.805967,2...          2051
2       248  4ba587fef964a520d40f39e3,1.321624,103.885401,2...          1584
3       412  4b8b40e6f964a5208d9932e3,1.325901,103.950987,2...          1482
4       221  4c8d9fc2509e3704b8d03d55,1.358358,103.959568,2...          1475
5       377  4cc2ad3f914137046410b655,1.345119,103.955474,2...          1405
6        16  4e94f6845c5c3201e8ea90f0,1.31079,103.72052,201...          1295
7       322  4b0bd124f964a520e03323e3,1.356685,103.988471,2...          1280
8       848  4b058816f964a520f0b022e3,1.352775,103.944939,2...          1193
9       912  4c4cc737a34b2d7f76883f98,1.355575,103.869633,2...          1145
10     1164  4b1baa07f964a52084fc23e3,1.35617,103.987033,20...          1041
11     1054  4d35592c2c76a1431dbd8dc7,1.332541,103.912833,2...          1039
12     1256  4e27f093483baa86515057b7,1.372333,103.949514,2...          1025
13      467  4b130770f964a520f49223e3,1.349391,103.873158,2...           949
14     1470  4d31b08e2c76a143d32b68c7,1.287848,103.832956,2...           811
15     2252  4b1537bbf964a5206ea923e3,1.294471,103.805967,2...           805
16     2391  4ec493204690b682a3daa006,1.334618,103.962319,2...           746
17      984  4be47d6fbcef2d7ff1a002e5,1.396473,103.908599,2...           741
18      437  4b10e2f1f964a5207b7623e3,1.34066,103.847194,20...           741
19     2768  4e1acb3545dd120c12246234,1.349458,103.931801,2...           738

In [13]:
len(user_trajs[73]), len(user_trajs[377]), len(user_trajs[912])

(11, 8, 6)

In [14]:
user_trajs[73]

[['4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-04-04 10:59:39',
  '4b2c0d8ff964a52086c024e3,1.31923,103.86157,2012-04-04 21:16:24',
  '4c061b6491d776b0655cf8f9,1.313242,103.871427,2012-04-04 21:39:48',
  '4c2c495db34ad13a901febce,1.314427,103.872597,2012-04-04 21:43:46',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-04-04 21:48:09',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-06 23:29:39',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-07 23:35:55',
  '4b78c916f964a5204ce22ee3,1.305082,103.881258,2012-04-08 11:12:59',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-08 11:24:41',
  '4be21632b02ec9b6cf364cc0,1.314701,103.872087,2012-04-08 14:33:44',
  '4f13bb64e4b000502e5db842,1.31483,103.871881,2012-04-08 14:34:16',
  '4b058819f964a520d4b122e3,1.321418,103.845949,2012-04-08 14:56:02',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-08 22:27:33',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-09 23:40:19',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-04-10 13:55:16',
  '4c2c3a9817a29c74aeb2e212,1.332447,103.848264,2012-04-10 14:36:40',
  '4b80c0cdf964a5202c8a30e3,1.332712,103.847987,2012-04-10 15:01:02',
  '4bd9734511dcc92808c5f933,1.332018,103.847732,2012-04-10 16:02:33',
  '4b0b5e4cf964a520e33023e3,1.332905,103.847054,2012-04-10 16:13:19',
  '4b5d2fe4f964a520f45529e3,1.332812,103.848072,2012-04-10 17:21:07',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-10 17:50:46',
  '4b0c75fcf964a520b83d23e3,1.306723,103.862616,2012-04-11 12:44:19',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-04-11 12:52:37',
  '4d2fdb6196fe6ea878041044,1.302832,103.857859,2012-04-11 13:15:17',
  '4b058814f964a52090b022e3,1.289798,103.855734,2012-04-11 13:50:51',
  '4e2d3b8ffa76bbf847eb4a06,1.29192,103.855409,2012-04-11 15:00:08',
  '4bc9936e511f9521e5e8adc7,1.32169,103.873803,2012-04-11 15:49:56',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-11 18:06:33',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-04-13 11:02:17',
  '4d82d10d99b78cfa60e3931f,1.312947,103.872736,2012-04-13 21:22:26',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-04-13 21:28:12',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-14 14:06:03',
  '4c273be4aa77ef3ba9e698b0,1.332101,103.913498,2012-04-14 20:29:19',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-14 21:22:47',
  '4d6a24636297721ec9bed1b5,1.323074,103.868959,2012-04-15 11:17:52',
  '4b1fa3b1f964a520982724e3,1.320002,103.861763,2012-04-17 17:10:20',
  '4b2c0d8ff964a52086c024e3,1.31923,103.86157,2012-04-17 17:11:29',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-17 22:14:49',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-20 10:11:01',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-04-20 10:56:28',
  '4d9059a25091a1cd0104b901,1.312476,103.872622,2012-04-20 11:26:31',
  '4c50edc3375c0f47fa701893,1.312879,103.874553,2012-04-20 11:27:03',
  '4bc99b9e511f95218ef1adc7,1.312494,103.872793,2012-04-20 11:34:56',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-04-20 11:38:15',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-20 15:32:47',
  '4d82d10d99b78cfa60e3931f,1.312947,103.872736,2012-04-20 21:12:43',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-04-20 22:14:23',
  '4b0bcea6f964a520c93323e3,1.308177,103.885818,2012-04-21 17:11:53',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-21 20:07:44',
  '4be2d629b02ec9b63cc94dc0,1.314423,103.878296,2012-04-22 11:50:32',
  '4bcbd9cb0687ef3bb584decc,1.317074,103.872954,2012-04-23 11:33:56',
  '4b058816f964a520f1b022e3,1.29654,103.853637,2012-04-23 12:08:26',
  '4b52a240f964a520838427e3,1.296469,103.85383,2012-04-23 12:12:10',
  '4b05880af964a520acad22e3,1.29812,103.855013,2012-04-23 12:58:10',
  '4b63cdd4f964a5205b922ae3,1.299766,103.85567,2012-04-23 13:45:10',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-04-23 14:04:09',
  '4b875431f964a520acbb31e3,1.300186,103.855117,2012-04-23 15:07:29',
  '4c08abe8009a0f470883e6bf,1.300449,103.85538,2012-04-23 15:27:25',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-04-23 15:33:54',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-04-23 15:49:00',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-23 15:57:40',
  '4c08b640ffb8c9b661b36861,1.3179,103.874316,2012-04-23 18:52:55',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-04-24 10:56:49',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-04-24 14:01:34',
  '4b8d235ef964a520d2e932e3,1.300653,103.855743,2012-04-24 15:10:11',
  '4baa04b7f964a52031443ae3,1.301063,103.855267,2012-04-24 15:10:53',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-04-24 15:59:46',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-04-24 16:13:32',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-24 17:36:20',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-04-25 20:10:18',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-04-26 14:29:46',
  '4b4040f6f964a5202db725e3,1.298872,103.855627,2012-04-26 15:43:26',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-04-26 17:26:12',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-04-26 17:44:22',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-26 20:21:47',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-27 20:26:48',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-04-29 11:46:06',
  '4b05880af964a520acad22e3,1.29812,103.855013,2012-04-29 12:50:29',
  '4b0eb596f964a520ea5923e3,1.296427,103.855432,2012-04-29 13:43:17',
  '4b083651f964a520660623e3,1.297821,103.854361,2012-04-29 14:11:47',
  '4bb9c1a6935e9521d3512790,1.299129,103.855391,2012-04-29 15:47:37',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-05-02 10:51:57',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-05-02 10:55:41',
  '4c3a88a5d94dc9b61d80fee7,1.302041,103.862477,2012-05-02 12:57:00',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-02 13:26:15',
  '4d2fdb6196fe6ea878041044,1.302832,103.857859,2012-05-02 13:26:49',
  '4b205bd1f964a5202a3124e3,1.300588,103.85612,2012-05-02 14:02:18',
  '4b8d235ef964a520d2e932e3,1.300653,103.855743,2012-05-02 15:11:28',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-05-02 15:23:40',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-05-02 15:39:34',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-02 18:51:12',
  '4b058818f964a520a7b122e3,1.264939,103.821668,2012-05-04 13:18:11',
  '4b755c0ef964a52022082ee3,1.263883,103.822861,2012-05-04 15:28:34',
  '4b66d786f964a520092d2be3,1.265213,103.82256,2012-05-04 15:39:28',
  '4d82d10d99b78cfa60e3931f,1.312947,103.872736,2012-05-04 20:17:12',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-05-04 20:21:27',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-05-07 09:24:22',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-05-07 09:25:28',
  '4f6be432e4b0d4a5af14dcc1,1.315457,103.871835,2012-05-07 09:29:04',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-07 10:40:20',
  '4be21632b02ec9b6cf364cc0,1.314701,103.872087,2012-05-07 12:56:17',
  '4b067155f964a520dfeb22e3,1.311545,103.871682,2012-05-07 13:02:05',
  '4b68d2b3f964a520c28e2be3,1.281345,103.839126,2012-05-07 13:18:12',
  '4b0a10cbf964a520752123e3,1.265406,103.821509,2012-05-07 13:25:34',
  '4b058818f964a520a7b122e3,1.264939,103.821668,2012-05-07 13:43:51',
  '4b3e00a4f964a520be9725e3,1.263776,103.821603,2012-05-07 15:46:19',
  '4b755c0ef964a52022082ee3,1.263883,103.822861,2012-05-07 16:33:24',
  '4b1fa3b1f964a520982724e3,1.320002,103.861763,2012-05-07 17:29:36',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-07 21:43:51',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-08 19:10:42',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-09 10:57:44',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-09 13:24:25',
  '4d2fdb6196fe6ea878041044,1.302832,103.857859,2012-05-09 13:25:39',
  '4df191afd1649c8a28db039c,1.321632,103.869423,2012-05-09 13:56:36',
  '4ca2d9e8d5a2a143e3824490,1.321273,103.870171,2012-05-09 14:46:52',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-09 15:17:41',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-09 20:44:47',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-11 11:01:52',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-11 13:51:09',
  '4b205bd1f964a5202a3124e3,1.300588,103.85612,2012-05-11 14:15:16',
  '4b68d2b3f964a520c28e2be3,1.281345,103.839126,2012-05-11 14:21:31',
  '4b0a10cbf964a520752123e3,1.265406,103.821509,2012-05-11 14:46:42',
  '4b058818f964a520a7b122e3,1.264939,103.821668,2012-05-11 14:52:11',
  '4b755c0ef964a52022082ee3,1.263883,103.822861,2012-05-11 14:56:38',
  '4b289bf4f964a520379424e3,1.264827,103.820141,2012-05-11 15:58:38',
  '4b67b69ef964a520ba5b2be3,1.265143,103.820066,2012-05-11 16:12:34',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-11 20:13:53',
  '4b05880ef964a520d6ae22e3,1.28984,103.845005,2012-05-11 20:58:36',
  '4b05880cf964a52046ae22e3,1.290484,103.845327,2012-05-12 02:20:51',
  '4df20817d4c01ff6b2e60583,1.309896,103.857572,2012-05-12 12:55:02',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-12 14:50:28',
  '4bdbf92563c5c9b6cb1b2a68,1.320388,103.885925,2012-05-13 10:34:49',
  '4b1bc985f964a5206afd23e3,1.317396,103.88586,2012-05-13 10:50:22',
  '4c9ed4c3d3c2b60c2487cfbc,1.345878,103.944675,2012-05-13 15:40:51',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-13 16:07:02',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-14 10:56:03',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-14 11:43:12',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-14 13:17:17',
  '4bc2bf7cabf49521e2edc293,1.300384,103.855647,2012-05-14 14:26:02',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-05-14 14:38:08',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-05-14 14:57:44',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-14 15:21:18',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-15 14:01:59',
  '4be79f5e88ed2d7f0600cb1d,1.303779,103.858562,2012-05-15 14:06:26',
  '4ca2d9e8d5a2a143e3824490,1.321273,103.870171,2012-05-15 14:26:47',
  '4fb202a6e4b0d2c83d08d23a,1.320299,103.869803,2012-05-15 15:15:57',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-15 16:14:36',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-16 10:56:00',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-16 13:43:48',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-16 20:43:21',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-16 22:04:14',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-17 11:02:31',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-05-17 11:05:43',
  '4b4c8a57f964a52090b526e3,1.303881,103.8612,2012-05-17 13:23:05',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-17 13:38:29',
  '4bc2bf7cabf49521e2edc293,1.300384,103.855647,2012-05-17 14:47:03',
  '4b99f642f964a520dc9835e3,1.301373,103.857731,2012-05-17 14:55:50',
  '4b1f8287f964a5209c2624e3,1.30138,103.857425,2012-05-17 14:57:16',
  '4b41945ef964a520a6c725e3,1.328369,103.887705,2012-05-17 15:09:58',
  '4ea0b0f22c5be3cf8c36d516,1.327965,103.887725,2012-05-17 15:11:44',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-17 16:44:25',
  '4bd2c92aa8b3a5932780685f,1.327371,103.927252,2012-05-19 18:40:20',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-19 21:04:38',
  '4f6be432e4b0d4a5af14dcc1,1.315457,103.871835,2012-05-22 10:54:34',
  '4d800615dbc5f04d7ba6f0b6,1.316867,103.872713,2012-05-22 10:55:26',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-22 10:58:03',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-22 11:37:23',
  '4bcbd9cb0687ef3bb584decc,1.317074,103.872954,2012-05-22 17:00:04',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-22 17:16:41',
  '4be79f5e88ed2d7f0600cb1d,1.303779,103.858562,2012-05-22 17:33:04',
  '4bfb62d7bbb7c928bc1d0843,1.303331,103.859636,2012-05-22 17:33:47',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-05-22 18:06:30',
  '4e8d501dd22d2a85bd9fc620,1.312022,103.872096,2012-05-22 19:41:46',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-22 19:52:17',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-05-24 11:05:56',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-05-24 11:06:19',
  '4d800615dbc5f04d7ba6f0b6,1.316867,103.872713,2012-05-24 11:41:54',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-24 11:44:12',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-24 13:12:44',
  '4b8d235ef964a520d2e932e3,1.300653,103.855743,2012-05-24 15:08:09',
  '4b205bd1f964a5202a3124e3,1.300588,103.85612,2012-05-24 15:09:06',
  '4b18e995f964a52079d623e3,1.334504,103.961542,2012-05-24 15:53:09',
  '4e925263e5fa72f70fba5010,1.33452,103.9624,2012-05-24 16:15:42',
  '4e9f88c393ad16f0cda640ff,1.334636,103.962506,2012-05-24 17:44:26',
  '4b18e995f964a52079d623e3,1.334504,103.961542,2012-05-24 18:00:16',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-27 09:23:27',
  '4c5509f2479fc9285e4e2294,1.33193,103.916889,2012-05-27 12:06:09',
  '4b594c74f964a5205a8428e3,1.353252,103.954396,2012-05-27 14:32:07',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-27 21:08:14',
  '4bcbd9cb0687ef3bb584decc,1.317074,103.872954,2012-05-28 13:38:36',
  '4bfb62d7bbb7c928bc1d0843,1.303331,103.859636,2012-05-28 13:51:55',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-05-28 14:06:15',
  '4ca18dbb54c8a1cd153aa94b,1.301075,103.855528,2012-05-28 15:02:40',
  '4b083651f964a520660623e3,1.297821,103.854361,2012-05-28 15:26:22',
  '4c848e5674d7b60c684c94d8,1.296458,103.852655,2012-05-28 16:06:24',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-05-28 16:23:56',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-05-28 16:32:19',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-05-29 09:54:41',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-05-29 09:55:01',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-05-29 09:55:26'],
 ['4becf35e91380f47b84f9f18,1.315315,103.872353,2012-05-29 09:56:03',
  '4df191afd1649c8a28db039c,1.321632,103.869423,2012-05-30 10:20:13',
  '4ca68edc76d3a0933aec026b,1.321809,103.869372,2012-05-30 10:23:26',
  '4b067155f964a520dfeb22e3,1.311545,103.871682,2012-05-30 13:15:49',
  '4b058819f964a520dfb122e3,1.293123,103.852376,2012-05-30 13:26:03',
  '4c848e5674d7b60c684c94d8,1.296458,103.852655,2012-06-01 17:13:41',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-06-01 17:37:08',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-01 20:51:32',
  '4d82d10d99b78cfa60e3931f,1.312947,103.872736,2012-06-01 21:15:10',
  '4bc99b9e511f95218ef1adc7,1.312494,103.872793,2012-06-01 21:16:18',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-01 23:23:41',
  '4b8367c2f964a520710531e3,1.314957,103.88074,2012-06-03 12:52:06',
  '4b05880af964a520adad22e3,1.291378,103.845071,2012-06-03 17:27:27',
  '4b058810f964a5203caf22e3,1.291812,103.845003,2012-06-03 17:29:50',
  '4b2cbd61f964a520e8c824e3,1.291288,103.845082,2012-06-03 17:30:55',
  '4b05880df964a5206bae22e3,1.290869,103.845726,2012-06-03 21:16:43',
  '4b058816f964a520f0b022e3,1.352775,103.944939,2012-06-04 21:09:16',
  '4cf6482fc020b60c9c2c1f75,1.352626,103.945055,2012-06-04 21:26:43',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-05 05:33:53',
  '4b07f6b3f964a520a10123e3,1.311234,103.856485,2012-06-05 13:39:38',
  '4f30cb65e4b0acb1eb34ac98,1.311012,103.856598,2012-06-05 13:56:19',
  '4b058815f964a520a9b022e3,1.310145,103.855216,2012-06-05 17:26:40',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-05 18:27:31',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-06 17:45:27',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-06-06 18:52:39',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-06-06 21:03:37',
  '4bde20e30ee3a593491c30b0,1.316967,103.878576,2012-06-07 11:03:10',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-07 13:10:22',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-08 19:15:24',
  '4c832ccad92ea093d6455272,1.32906,103.929798,2012-06-09 17:21:22',
  '4bd2c92aa8b3a5932780685f,1.327371,103.927252,2012-06-09 19:01:36',
  '4e2ffd588877341a51578335,1.327426,103.92747,2012-06-09 19:03:08',
  '4d82d10d99b78cfa60e3931f,1.312947,103.872736,2012-06-09 20:29:29',
  '4c024271f56c2d7f4f301b66,1.312741,103.873104,2012-06-09 20:31:17',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-09 22:33:58',
  '4b694186f964a5200a9d2be3,1.305533,103.881724,2012-06-10 11:13:23',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-10 14:29:25',
  '4c555ef31b46c9b6c9331dd0,1.320943,103.870545,2012-06-10 17:46:08',
  '4fb202a6e4b0d2c83d08d23a,1.320299,103.869803,2012-06-10 17:46:41',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-10 22:53:26',
  '4b0bd124f964a520e03323e3,1.356685,103.988471,2012-06-11 05:54:02',
  '4b0bd124f964a520e03323e3,1.356685,103.988471,2012-06-15 20:03:21',
  '4bc6e168af07a593f32e7e2d,1.308547,103.932896,2012-06-15 20:48:38',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-15 21:49:06',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-06-18 09:00:23',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-06-18 09:02:37',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-06-18 09:24:44',
  '4f13bb64e4b000502e5db842,1.31483,103.871881,2012-06-18 09:37:15',
  '4be21632b02ec9b6cf364cc0,1.314701,103.872087,2012-06-18 09:38:09',
  '4bc9936e511f9521e5e8adc7,1.32169,103.873803,2012-06-18 09:52:55',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-18 10:34:24',
  '4c2dafb67d85a593450053f3,1.315108,103.872415,2012-06-18 11:30:56',
  '4c56b1e030d82d7f5007d862,1.314693,103.871983,2012-06-18 11:32:56',
  '4becf35e91380f47b84f9f18,1.315315,103.872353,2012-06-18 11:38:24',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-18 12:37:17',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-06-18 14:09:31',
  '4bc6ecab15a7ef3b3f7378da,1.319944,103.861858,2012-06-18 14:29:03',
  '4bc6e7916501c9b631753d29,1.319788,103.861914,2012-06-18 14:54:30',
  '4d1085f771e8a1cdd71581bd,1.321165,103.862996,2012-06-18 15:01:07',
  '4b1fa3b1f964a520982724e3,1.320002,103.861763,2012-06-18 16:06:33',
  '4cb7063ee262b60c140f73e0,1.31906,103.862221,2012-06-18 16:27:22',
  '4c061b6491d776b0655cf8f9,1.313242,103.871427,2012-06-18 17:06:12',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-18 17:53:29',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-21 08:35:41',
  '4baf04b2f964a52029e73be3,1.315017,103.871744,2012-06-21 09:42:40',
  '4d800c3ea4e237044e68adcc,1.315365,103.872872,2012-06-21 09:44:04',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-21 13:56:52',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-06-27 13:35:39',
  '4b8c9f75f964a52091d832e3,1.315733,103.883221,2012-06-27 13:48:18',
  '4ba587fef964a520d40f39e3,1.321624,103.885401,2012-06-27 15:55:17',
  '4c64dbf05e61d13af494ba85,1.318785,103.88666,2012-06-27 15:59:48',
  '4cc5932fc844721e54cbef01,1.310746,103.87338,2012-06-27 16:17:13',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-06-27 16:56:31',
  '4b9096c6f964a5203b9133e3,1.315508,103.8726,2012-06-27 20:42:23',
  '4b596db4f964a520fd8728e3,1.31871,103.861326,2012-07-01 10:02:27',
  '4b2c0d8ff964a52086c024e3,1.31923,103.86157,2012-07-01 10:42:02',
  '4cb7063ee262b60c140f73e0,1.31906,103.862221,2012-07-01 10:42:59',
  '4bcc6df73740b7130bf56365,1.321514,103.859714,2012-07-01 10:54:52',
  '4b9f189df964a5207a1337e3,1.32169,103.873803,2012-07-01 11:14:38',
  '4c08b640ffb8c9b661b36861,1.3179,103.874316,2012-07-02 18:39:08',
  '4bc9936e511f9521e5e8adc7,1.32169,103.873803,2012-07-02 18:51:26',
  '4b9662ecf964a5206ac934e3,1.30003,103.855155,2012-07-03 17:23:08',
  '4bd4d1066798ef3b357b628d,1.316323,103.873458,2012-07-03 17:41:31',
  '4bcbe0333740b7139a516365,1.303741,103.857408,2012-07-04 12:45:55',
  '4d2fdb6196fe6ea878041044,1.302832,103.857859,2012-07-04 13:28:41',
  '4baa04b7f964a52031443ae3,1.301063,103.855267,2012-07-04 14:09:26',
  '4bcb143768f976b0eb516083,1.302165,103.857729,2012-07-04 14:34:13',

In [15]:
num_traj = 0
num_user = 0
for user, trajs in user_trajs.items():
    if len(trajs) > 0:
        num_user += 1
        num_traj += len(trajs)
num_user, num_traj

(4654, 5073)

In [16]:
num_records = user_checkins['num_checkins'].sum()

num_records

np.int64(308825)

In [17]:
user_traj_num = {}
for user, trajs in user_trajs.items():
    num = len(trajs)
    print(user, num)
    if num not in user_traj_num:
        user_traj_num[num] = 1
    else:
        user_traj_num[num] += 1

user_traj_num = dict(sorted(user_traj_num.items(), key=lambda item: item[0]))
user_traj_num

16 7
51 1
73 11
126 4
142 1
143 11
151 1
208 1
210 2
221 8
222 1
237 1
248 8
289 2
296 2
310 3
322 7
348 1
354 4
377 8
412 8
437 4
467 5
559 1
574 1
623 1
653 1
667 1
683 1
800 3
814 1
848 6
888 2
907 1
912 6
957 4
984 4
994 1
1011 2
1014 1
1035 2
1041 1
1054 6
1055 1
1072 1
1129 1
1164 6
1212 1
1256 6
1304 4
1317 1
1326 1
1402 3
1410 4
1470 5
1495 1
1515 1
1543 1
1565 1
1606 1
1610 1
1623 2
1724 1
1760 1
1767 1
1772 2
1776 1
1785 1
1865 3
1889 1
1925 1
1929 1
1986 1
1988 1
1997 4
2008 1
2062 1
2108 1
2113 1
2126 3
2135 2
2159 1
2189 1
2219 1
2228 3
2234 1
2245 1
2252 5
2288 1
2305 1
2306 1
2317 2
2364 1
2371 4
2390 1
2391 4
2400 4
2445 1
2504 1
2537 1
2594 1
2619 1
2662 1
2736 3
2739 1
2746 1
2768 4
2770 3
2789 1
2820 1
2862 3
2877 2
2924 1
2941 4
2967 3
2978 3
3015 1
3033 1
3034 1
3040 1
3075 1
3114 1
3154 2
3172 1
3199 2
3209 1
3260 1
3307 1
3349 4
3361 1
3364 1
3378 1
3460 1
3461 1
3476 1
3516 1
3519 1
3520 1
3524 1
3531 1
3544 1
3559 1
3579 1
3591 1
3594 1
3606 1
3671 2
3749 1
3767 1
3770 1
3785 3
3797 3
3829 1
3842 2
3855 3
3856 1
3897 1
3955 2
3985 1
4000 1
4029 2
4041 1
4047 4
4058 1
4068 1
4095 1
4119 2
4121 1
4212 1
4215 3
4239 4
4264 1
4275 1
4296 1
4316 1
4330 1
4400 2
4401 1
4402 3
4441 4
4519 1
4556 1
4583 1
4588 1
4599 1
4667 3
4678 3
4687 3
4757 1
4758 1
4774 1
4813 1
4816 1
4860 2
4865 3
4876 2
4945 1
4978 2
4989 3
5113 1
5179 1
5181 1
5221 4
5269 1
5276 1
5287 3
5307 1
5311 1
5354 2
5358 1
5427 1
5511 3
5525 1
5607 1
5672 1
5704 1
5740 1
5817 1
5834 1
5845 1
5896 1
5918 1
5948 3
6017 1
6067 3
6147 1
6214 1
6218 1
6225 1
6276 1
6305 3
6325 1
6335 1
6342 3
6352 1
6398 1
6425 1
6453 1
6509 1
6512 1
6535 1
6541 1
6565 1
6567 1
6588 1
6601 1
6616 1
6624 1
6704 1
6706 1
6791 1
6838 1
6845 1
6848 1
6866 1
6877 1
6909 1
6957 1
7015 1
7035 1
7050 2
7076 1
7087 1
7102 1
7153 1
7177 1
7179 1
7312 1
7406 1
7449 1
7472 1
7532 3
7541 2
7552 1
7589 1
7659 1
7667 1
7669 1
7751 3
7866 1
7888 1
7917 1
7932 1
7973 2
8005 1
8025 1
8029 3
8030 1
8066 1
8127 1
8132 1
8139 1
8165 1
8173 3
8253 2
8273 1
8288 1
8291 1
8337 1
8464 1
8477 1
8490 1
8508 1
8531 1
8544 1
8557 1
8568 2
8592 1
8780 1
8796 2
8847 1
8849 2
8876 1
9040 1
9043 1
9098 1
9108 1
9111 3
9165 2
9234 3
9277 1
9318 3
9339 1
9344 1
9407 1
9425 1
9446 2
9450 1
9473 1
9533 1
9581 1
9613 1
9743 1
9824 1
9828 1
9839 1
9860 1
9940 1
9968 1
9975 1
9984 1
9992 1
10032 1
10033 1
10071 2
10082 1
10194 2
10269 1
10272 1
10273 1
10337 2
10351 2
10359 1
10366 1
10412 1
10474 1
10486 1
10502 1
10521 1
10530 1
10585 1
10618 1
10665 3
10672 1
10697 1
10728 1
10748 2
10784 1
10796 1
10887 1
10957 1
10964 1
10968 1
10989 1
11061 1
11063 2
11066 1
11077 1
11126 1
11130 1
11133 1
11135 2
11160 1
11195 2
11211 1
11214 1
11241 1
11426 1
11431 2
11499 1
11546 1
11562 1
11627 1
11655 1
11711 1
11713 1
11804 1
11869 1
11915 3
11922 2
12006 1
12012 1
12019 1
12109 1
12128 1
12207 1
12304 2
12390 1
12391 1
12443 2
12482 2
12517 2
12567 1
12590 1
12608 1
12623 1
12700 1
12763 2
12764 2
12830 2
12846 1
12872 1
12934 2
12995 1
13052 1
13081 1
13115 1
13131 1
13173 1
13237 1
13269 1
13271 1
13322 2
13323 1
13358 2
13409 1
13547 1
13552 1
13554 2
13591 2
13598 1
13764 1
13782 1
13826 1
13869 1
13904 2
13985 1
13991 1
14007 1
14075 1
14083 1
14088 1
14102 1
14106 2
14139 1
14144 2
14155 1
14174 2
14187 1
14263 1
14283 1
14313 1
14355 2
14388 2
14462 1
14502 2
14588 1
14680 1
14697 1
14744 1
14768 1
14808 1
14847 1
14850 1
14852 1
14868 1
14883 1
14922 2
14948 1
15009 1
15018 1
15098 2
15100 1
15155 1
15161 1
15198 1
15259 2
15280 1
15360 1
15402 1
15439 1
15466 1
15508 1
15565 1
15609 1
15612 1
15681 1
15724 1
15757 1
15778 1
15783 2
15944 1
15991 1
16045 2
16072 1
16073 2
16130 1
16135 2
16143 1
16207 1
16222 1
16228 1
16273 1
16288 1
16315 1
16330 1
16348 1
16436 1
16460 2
16510 2
16522 1
16524 2
16539 1
16550 2
16581 2
16618 1
16621 2
16634 1
16711 1
16728 1
16746 1
16774 1
16809 2
16877 1
16892 2
16953 1
17104 1
17272 2
17330 1
17353 1
17366 1
17370 1
17397 1
17409 1
17448 1
17465 1
17488 1
17534 1
17559 1
17593 1
17641 1
17657 1
17702 2
17745 2
17766 1
17794 1
17813 1
17873 1
17875 1
17898 1
17922 1
18034 1
18045 2
18088 1
18117 1
18164 1
18246 2
18252 1
18277 2
18337 1
18353 1
18394 1
18402 1
18425 1
18473 1
18563 1
18582 1
18624 1
18633 1
18683 1
18700 1
18723 1
18733 1
18739 2
18783 1
18792 1
18823 2
18840 1
18904 1
19030 1
19031 2
19044 1
19070 1
19071 2
19138 1
19139 1
19222 2
19261 2
19370 2
19386 1
19413 1
19441 1
19503 2
19509 1
19522 1
19532 1
19569 1
19579 2
19626 2
19655 1
19660 1
19671 2
19690 1
19734 1
19739 1
19766 1
19775 1
19787 1
19914 1
19970 1
20024 1
20072 1
20134 1
20159 2
20202 1
20226 1
20254 1
20263 1
20270 1
20292 1
20297 1
20330 1
20331 1
20385 1
20428 1
20495 1
20504 1
20509 1
20526 1
20528 2
20542 1
20633 2
20648 1
20682 2
20746 1
20778 1
20834 1
20856 1
20898 1
20908 1
21029 1
21033 2
21051 1
21070 1
21113 1
21292 2
21303 1
21384 1
21396 1
21418 1
21648 1
21689 1
21723 1
21942 1
21956 1
21990 1
22004 1
22028 1
22080 2
22136 1
22156 2
22240 1
22254 1
22320 2
22446 1
22458 2
22547 1
22608 2
22620 1
22634 2
22686 1
22809 2
22810 1
22906 1
22975 2
23222 2
23237 2
23260 1
23268 1
23286 1
23317 1
23416 1
23519 2
23632 2
23633 1
23634 1
23635 1
23679 1
23686 1
23863 1
23880 1
23888 2
23936 1
23956 2
23973 1
23981 1
23992 1
24008 1
24045 2
24109 1
24112 1
24118 1
24127 1
24144 2
24323 2
24339 1
24347 1
24401 1
24468 2
24525 1
24592 1
24604 1
24610 1
24615 2
24620 1
24639 1
24654 1
24695 1
24746 1
24765 1
24821 1
24864 2
24939 2
24959 1
24990 1
24999 2
25014 1
25103 1
25178 1
25181 2
25338 1
25369 1
25426 1
25444 1
25462 2
25478 2
25572 1
25593 1
25709 1
25747 1
25808 1
25812 2
25828 1
25835 1
25889 1
25890 1
25948 1
25961 2
26006 1
26108 1
26131 1
26147 1
26192 1
26320 1
26349 1
26471 2
26486 1
26489 1
26519 1
26534 1
26635 1
26678 1
26711 1
26720 1
26730 2
26733 1
26777 1
26826 1
27038 1
27066 2
27098 1
27125 1
27160 1
27201 1
27216 1
27236 1
27362 1
27604 1
27693 1
27695 1
27760 2
27777 1
27780 1
27832 1
27836 2
27863 1
27871 1
27877 2
27976 1
27989 2
28002 1
28039 2
28042 1
28084 1
28120 2
28196 1
28239 1
28298 1
28325 1
28409 1
28416 2
28443 2
28500 1
28569 1
28616 1
28670 1
28728 1
28793 1
28802 1
28816 1
28847 1
28865 1
28891 2
28903 1
28914 1
28928 1
29031 2
29055 2
29080 1
29140 2
29153 1
29239 1
29353 1
29462 1
29467 1
29485 1
29567 1
29568 1
29623 1
29629 1
29651 1
29697 1
29748 1
29890 2
29903 1
29905 1
29961 1
30043 1
30093 1
30095 1
30124 1
30163 1
30182 1
30240 1
30288 2
30313 1
30328 1
30378 2
30472 1
30474 1
30519 1
30529 1
30543 1
30558 1
30580 1
30666 1
30681 1
30719 1
30720 1
30794 2
30863 1
30892 2
31004 1
31009 1
31086 1
31130 1
31154 1
31155 1
31165 1
31188 1
31248 1
31380 2
31452 2
31511 1
31525 2
31536 2
31561 2
31574 1
31581 1
31623 2
31656 1
31672 2
31728 1
31758 1
31774 1
31903 1
31913 1
32045 1
32094 2
32099 1
32168 1
32251 1
32284 1
32345 2
32357 1
32362 1
32512 1
32576 1
32621 1
32629 1
32688 1
32701 1
32712 1
32723 1
32753 1
32825 1
32839 1
32841 2
32945 2
33013 1
33025 1
33177 1
33204 1
33298 1
33397 1
33443 1
33534 1
33557 1
33591 1
33690 2
33703 1
33774 1
33778 1
33780 1
33914 1
33951 1
34056 1
34175 1
34222 1
34229 2
34282 2
34305 1
34315 1
34376 1
34402 2
34417 1
34422 1
34430 1
34444 1
34492 1
34497 2
34530 1
34531 1
34662 2
34664 1
34670 1
34696 1
34755 1
34763 1
34815 1
34837 1
34936 1
34950 1
34952 1
34987 1
35022 1
35088 1
35181 1
35214 1
35222 1
35267 1
35291 1
35300 1
35446 2
35577 1
35727 1
35748 1
35756 1
35789 1
35841 2
36008 1
36060 2
36087 1
36129 1
36160 1
36162 1
36271 2
36409 1
36523 1
36546 1
36556 1
36573 1
36622 1
36653 1
36656 1
36678 1
36723 1
36803 1
36819 1
36853 1
36899 1
36910 1
36989 1
37027 1
37056 1
37073 1
37160 1
37170 1
37184 1
37217 1
37270 1
37294 1
37295 2
37305 1
37378 1
37451 1
37468 1
37622 1
37630 1
37636 1
37652 1
37654 1
37661 1
37669 1
37683 1
37715 1
37743 1
37772 1
37802 1
37841 2
37956 1
37968 1
37970 1
38081 1
38114 1
38133 1
38192 2
38208 1
38263 1
38334 1
38475 1
38493 1
38507 1
38520 2
38532 1
38549 1
38573 1
38585 1
38613 1
38631 1
38759 1
38760 1
38801 1
38862 1
38921 1
38934 1
38935 1
38941 1
39028 1
39037 1
39182 2
39191 1
39315 2
39338 1
39397 1
39403 1
39404 2
39408 1
39424 1
39425 1
39481 1
39518 1
39625 1
39762 1
39822 1
39848 1
39851 1
39863 1
39888 1
39997 2
40055 2
40170 1
40332 1
40340 1
40375 1
40405 1
40460 1
40672 1
40683 1
40697 1
40714 1
40734 1
40754 1
40774 2
40775 2
40776 2
40804 1
40817 1
40970 1
40986 1
40991 1
40994 1
41001 1
41081 1
41091 2
41160 1
41303 1
41323 1
41373 1
41416 2
41420 1
41452 1
41534 1
41607 1
41640 1
41692 2
41716 1
41719 1
41738 2
41747 1
41759 1
41768 1
41779 2
41798 1
41823 1
41912 1
41936 2
41957 1
41958 1
41964 1
41976 1
42023 1
42025 1
42027 1
42065 1
42099 1
42177 1
42277 1
42283 1
42286 1
42300 1
42375 1
42376 1
42381 1
42603 1
42662 1
42793 1
42903 1
42910 1
42943 1
43045 1
43094 1
43095 1
43166 1
43211 1
43250 1
43264 1
43362 1
43391 1
43422 1
43440 1
43495 1
43560 1
43600 1
43610 1
43651 1
43668 1
43725 1
43785 1
43888 1
43891 2
43932 1
44010 1
44035 1
44052 1
44271 1
44288 1
44304 1
44312 1
44366 1
44382 1
44477 1
44483 1
44557 1
44634 1
44654 1
44663 1
44677 1
44700 1
44729 1
44773 1
44805 1
44808 1
44985 1
45019 1
45021 1
45032 2
45037 1
45041 2
45086 1
45166 1
45284 1
45285 1
45319 1
45323 1
45329 1
45360 1
45395 1
45424 1
45463 1
45662 1
45710 1
45950 1
45986 1
46019 1
46043 1
46044 1
46062 1
46106 1
46116 1
46185 1
46193 1
46216 1
46324 1
46391 1
46405 1
46469 1
46509 1
46581 1
46590 1
46593 2
46594 1
46632 1
46639 1
46853 1
46881 1
46890 1
47153 1
47167 1
47227 1
47295 2
47344 1
47349 1
47350 1
47382 1
47402 1
47497 1
47580 1
47626 1
47727 2
47780 1
47812 1
47826 1
47955 1
47967 1
48006 1
48070 1
48098 1
48148 1
48189 1
48243 1
48263 2
48380 1
48412 1
48415 1
48491 1
48540 1
48575 1
48638 1
48681 1
48739 1
48792 2
48809 1
48815 1
48933 1
48954 1
48959 1
49100 1
49206 1
49270 1
49294 1
49304 1
49341 1
49385 1
49386 1
49530 1
49607 1
49649 1
49677 1
49708 1
49777 1
49801 1
49812 1
49875 1
49930 1
49984 1
50015 1
50041 1
50042 1
50065 1
50071 1
50117 1
50211 1
50244 1
50280 1
50570 1
50623 1
50643 1
50740 1
50817 1
50828 1
50849 2
51184 1
51236 1
51253 1
51280 1
51283 1
51288 1
51305 1
51308 1
51338 1
51349 1
51395 1
51533 1
51677 1
51697 1
51757 1
51792 1
51867 1
51880 1
51892 1
52022 1
52137 1
52170 2
52185 1
52218 1
52245 1
52357 1
52438 1
52600 1
52611 1
52647 1
52735 1
52739 1
52761 1
52788 1
52987 1
53035 1
53042 1
53054 1
53057 1
53129 1
53152 1
53158 1
53214 1
53224 1
53232 1
53233 1
53390 1
53405 1
53428 1
53463 1
53467 1
53476 1
53488 1
53505 1
53601 1
53624 1
53658 1
53673 1
53726 1
53742 1
53751 1
53779 1
53918 1
53920 1
53959 1
53982 1
53989 1
54004 1
54058 1
54126 1
54169 1
54172 1
54180 1
54189 1
54295 1
54317 1
54343 1
54415 1
54464 1
54519 1
54926 1
55088 1
55111 1
55120 1
55138 1
55151 2
55176 1
55180 1
55191 1
55210 1
55249 1
55363 1
55371 1
55445 1
55462 1
55678 1
55760 1
55783 1
55813 1
55816 1
55918 1
55935 1
55980 1
55983 1
56030 1
56054 1
56295 1
56317 1
56325 1
56333 1
56334 1
56351 1
56352 1
56371 1
56550 1
56573 1
56597 1
56681 1
56682 1
56776 1
56817 1
56822 1
56896 1
56947 1
57001 1
57025 1
57107 1
57172 1
57242 1
57252 1
57286 1
57358 1
57367 1
57474 1
57484 1
57512 1
57517 1
57550 1
57570 1
57613 1
57680 1
57715 1
57732 1
57740 1
57855 1
57860 1
57869 1
57877 1
58006 1
58030 1
58056 1
58072 1
58137 1
58328 1
58342 1
58421 1
58434 1
58515 1
58552 1
58561 1
58602 1
58912 1
58923 1
58970 1
58974 1
59018 1
59037 1
59157 1
59186 1
59207 1
59228 1
59259 1
59342 1
59347 1
59382 1
59384 1
59403 1
59443 1
59508 1
59514 1
59590 1
59598 1
59655 1
59667 1
59670 1
59726 1
59831 1
59832 1
59841 1
59856 1
59931 1
59945 1
59952 1
60087 1
60126 1
60356 1
60380 1
60385 1
60483 1
60490 1
60516 1
60596 1
60652 1
60712 1
60744 1
60826 1
60830 1
60831 1
60835 1
60853 1
60881 1
60896 1
60979 1
61084 1
61100 1
61108 1
61130 1
61138 1
61152 1
61232 1
61339 1
61447 1
61491 1
61540 1
61595 1
61750 1
61854 1
61866 1
61928 1
61930 1
61976 1
61979 1
62004 1
62068 1
62076 1
62409 1
62429 1
62452 1
62613 1
62621 1
62627 1
62654 1
62656 1
62716 1
62782 1
63022 1
63023 1
63025 1
63073 1
63113 1
63114 1
63186 1
63226 1
63254 1
63277 1
63278 1
63284 1
63289 1
63360 1
63554 1
63599 1
63625 1
63664 1
63665 1
63711 1
63734 1
63847 1
63882 1
63938 1
64051 1
64094 1
64102 1
64148 1
64150 1
64157 1
64179 1
64208 1
64251 1
64254 1
64258 1
64278 1
64327 1
64335 1
64349 1
64506 1
64513 1
64528 1
64633 1
64648 1
64707 1
64718 1
64722 1
64763 1
64777 1
64797 1
64815 1
64850 1
64891 1
65124 1
65292 1
65349 1
65359 1
65412 1
65506 1
65582 1
65665 1
65679 1
65695 1
65725 1
65882 1
65914 1
65994 1
66002 1
66005 1
66037 1
66067 1
66144 1
66149 1
66153 1
66185 1
66194 1
66203 1
66214 1
66263 1
66339 1
66431 1
66492 1
66573 1
66605 1
66680 1
66930 1
67045 1
67081 1
67085 1
67113 1
67135 1
67183 1
67188 1
67190 1
67213 1
67265 1
67281 1
67331 1
67422 1
67438 1
67462 1
67468 1
67503 1
67544 1
67694 1
67708 1
67724 1
67789 1
67874 1
68096 1
68106 1
68163 1
68293 1
68324 1
68331 1
68364 1
68427 1
68446 1
68453 1
68577 1
68649 1
68735 1
68967 1
69027 1
69047 1
69070 1
69071 1
69086 1
69112 1
69158 1
69215 1
69222 1
69290 1
69328 1
69579 1
69692 1
69723 1
69724 1
69758 1
69808 1
69859 1
69904 1
69937 1
69949 1
69991 1
70022 1
70133 1
70205 1
70242 1
70277 1
70374 1
70381 1
70438 1
70461 1
70484 1
70501 1
70507 1
70511 1
70530 1
70554 1
70645 1
70813 1
70870 1
70908 1
70963 1
70991 1
71076 1
71133 1
71134 1
71149 1
71154 1
71167 1
71426 1
71476 1
71688 1
71720 1
71765 1
71769 1
71781 1
71796 1
71992 1
72021 1
72098 1
72134 1
72151 1
72165 1
72251 1
72276 1
72279 1
72289 1
72391 1
72423 1
72427 1
72463 1
72506 1
72574 1
72632 1
72738 1
72791 1
72795 1
72908 1
72947 1
72963 1
72973 1
72985 1
73073 1
73096 1
73355 1
73509 1
73526 1
73539 1
73636 1
73665 1
73719 1
73767 1
73775 1
73875 1
73878 1
74008 1
74052 1
74111 1
74138 1
74201 1
74228 1
74268 1
74283 1
74343 1
74407 1
74478 1
74486 1
74547 1
74559 1
74568 1
74605 1
74611 1
74729 1
74792 1
74814 1
74835 1
74935 1
74946 1
75178 1
75200 1
75268 1
75313 1
75322 1
75328 1
75364 1
75374 1
75507 1
75575 1
75671 1
75686 1
75687 1
75704 1
75741 1
75779 1
75795 1
75820 1
75866 1
76124 1
76143 1
76165 1
76266 1
76341 1
76342 1
76383 1
76401 1
76403 1
76462 1
76472 1
76509 1
76631 1
76783 1
76811 1
76820 1
76981 1
77081 1
77093 1
77124 1
77191 1
77196 1
77211 1
77334 1
77397 1
77520 1
77773 1
77777 1
77805 1
77808 1
77891 1
77930 1
78025 1
78031 1
78074 1
78111 1
78157 1
78162 1
78184 1
78426 1
78479 1
78498 1
78501 1
78509 1
78538 1
78539 1
78564 1
78571 1
78593 1
78633 1
78704 1
78756 1
78766 1
78790 1
78837 1
78848 1
78972 1
79003 1
79052 1
79065 1
79128 1
79236 1
79241 1
79344 1
79455 1
79510 1
79518 1
79566 1
79570 1
79583 1
79585 1
79653 1
79760 1
79764 1
79799 1
79974 1
79986 1
80013 1
80103 1
80154 1
80163 1
80212 1
80219 1
80240 1
80252 1
80292 1
80317 1
80339 1
80344 1
80605 1
80609 1
80646 1
80791 1
80836 1
80955 1
80968 1
81046 1
81091 1
81092 1
81102 1
81133 1
81136 1
81193 1
81515 1
81557 1
81560 1
81564 1
81578 1
81589 1
81649 1
81706 1
81736 1
81781 1
81782 1
81793 1
81809 1
81821 1
81858 1
81882 1
81913 1
82055 1
82056 1
82282 1
82310 1
82373 1
82417 1
82421 1
82433 1
82438 1
82445 1
82525 1
82664 1
82742 1
82754 1
82779 1
82883 1
82921 1
82971 1
82985 1
83083 1
83156 1
83197 1
83256 1
83280 1
83290 1
83451 1
83483 1
83628 1
83674 1
83784 1
83819 1
83879 1
84027 1
84059 1
84064 1
84069 1
84093 1
84170 1
84256 1
84366 1
84519 1
84539 1
84688 1
84837 1
84885 1
84995 1
85007 1
85064 1
85101 1
85219 1
85243 1
85251 1
85284 1
85338 1
85383 1
85430 1
85692 1
85698 1
85711 1
85717 1
85719 1
85720 1
85731 1
85783 1
85835 1
85836 1
85861 1
85872 1
85890 1
85913 1
86092 1
86171 1
86191 1
86347 1
86422 1
86523 1
86536 1
86599 1
86644 1
86657 1
86707 1
86730 1
86739 1
86754 1
86780 1
86790 1
86791 1
86798 1
86879 1
86901 1
86902 1
86904 1
86929 1
87016 1
87051 1
87100 1
87103 1
87178 1
87271 1
87305 1
87417 1
87471 1
87480 1
87514 1
87863 1
87874 1
87912 1
87925 1
87944 1
87991 1
88010 1
88312 1
88356 1
88367 1
88371 1
88414 1
88495 1
88567 1
88752 1
88829 1
88844 1
88929 1
88976 1
89122 1
89235 1
89273 1
89290 1
89310 1
89315 1
89325 1
89399 1
89437 1
89442 1
89526 1
89553 1
89623 1
89624 1
89652 1
89690 1
89773 1
89811 1
89865 1
89905 1
89974 1
90005 1
90072 1
90130 1
90135 1
90155 1
90215 1
90216 1
90218 1
90256 1
90288 1
90407 1
90419 1
90501 1
90629 1
90632 1
90634 1
90712 1
90754 1
90964 1
90976 1
91002 1
91021 1
91049 1
91098 1
91183 1
91194 1
91238 1
91257 1
91420 1
91423 1
91544 1
91614 1
91934 1
91936 1
92267 1
92315 1
92337 1
92394 1
92407 1
92413 1
92560 1
92563 1
92724 1
92735 1
92815 1
92871 1
92882 1
92890 1
92897 1
93012 1
93066 1
93112 1
93193 1
93220 1
93224 1
93283 1
93289 1
93454 1
93620 1
93629 1
93647 1
93761 1
93870 1
93878 1
93911 1
93919 1
93959 1
94114 1
94183 1
94345 1
94361 1
94374 1
94513 1
94569 1
94759 1
94785 1
94816 1
94846 1
94860 1
94870 1
94907 1
94912 1
94934 1
94940 1
94981 1
94993 1
95038 1
95044 1
95058 1
95096 1
95119 1
95275 1
95427 1
95750 1
95766 1
95782 1
95828 1
95885 1
95924 1
95981 1
96043 1
96083 1
96121 1
96152 1
96216 1
96225 1
96344 1
96396 1
96490 1
96539 1
96707 1
96714 1
96736 1
96739 1
96773 1
96788 1
96870 1
96874 1
96992 1
97027 1
97082 1
97121 1
97122 1
97179 1
97187 1
97189 1
97286 1
97359 1
97704 1
97857 1
97872 1
97906 1
97910 1
97921 1
97963 1
97967 1
98006 1
98033 1
98035 1
98104 1
98121 1
98151 1
98159 1
98180 1
98393 1
98564 1
98734 1
98776 1
98792 1
98846 1
98887 1
98971 1
98994 1
99032 1
99041 1
99047 1
99087 1
99113 1
99179 1
99188 1
99296 1
99415 1
99511 1
99598 1
99693 1
99727 1
99784 1
99807 1
99819 1
99821 1
99927 1
99934 1
99937 1
99945 1
100078 1
100081 1
100183 1
100246 1
100253 1
100354 1
100362 1
100387 1
100412 1
100444 1
100770 1
100781 1
100788 1
100791 1
100801 1
100814 1
100822 1
100835 1
100836 1
100989 1
101029 1
101081 1
101154 1
101196 1
101275 1
101296 1
101300 1
101306 1
101396 1
101414 1
101435 1
101817 1
101860 1
101864 1
101905 1
102133 1
102137 1
102166 1
102268 1
102281 1
102323 1
102422 1
102439 1
102459 1
102466 1
102504 1
102767 1
102842 1
102900 1
102965 1
102980 1
103010 1
103068 1
103177 1
103213 1
103294 1
103323 1
103345 1
103367 1
103368 1
103458 1
103495 1
103595 1
103642 1
103700 1
103713 1
103739 1
103741 1
104049 1
104055 1
104079 1
104081 1
104131 1
104186 1
104246 1
104314 1
104330 1
104434 1
104441 1
104443 1
104774 1
104833 1
104983 1
105017 1
105049 1
105124 1
105140 1
105144 1
105151 1
105198 1
105211 1
105225 1
105292 1
105361 1
105409 1
105413 1
105428 1
105475 1
105493 1
105512 1
105544 1
105568 1
105592 1
105599 1
105636 1
105662 1
105694 1
105743 1
105946 1
106250 1
106271 1
106370 1
106388 1
106395 1
106399 1
106404 1
106453 1
106474 1
106573 1
106609 1
106718 1
106936 1
106977 1
107025 1
107135 1
107292 1
107300 1
107315 1
107384 1
107428 1
107485 1
107522 1
107530 1
107686 1
107741 1
107777 1
107828 1
107935 1
108010 1
108021 1
108029 1
108067 1
108228 1
108262 1
108393 1
108510 1
108665 1
108710 1
108728 1
108848 1
108999 1
109036 1
109081 1
109105 1
109147 1
109216 1
109262 1
109263 1
109286 1
109299 1
109337 1
109422 1
109573 1
109603 1
109609 1
109768 1
109775 1
109811 1
109825 1
109830 1
110087 1
110089 1
110126 1
110150 1
110168 1
110198 1
110258 1
110270 1
110309 1
110310 1
110334 1
110405 1
110425 1
110442 1
110578 1
110626 1
110636 1
110957 1
110989 1
110993 1
111032 1
111129 1
111152 1
111241 1
111347 1
111371 1
111406 1
111472 1
111478 1
111541 1
111692 1
111777 1
111889 1
111894 1
111935 1
112098 1
112117 1
112178 1
112206 1
112218 1
112243 1
112299 1
112332 1
112416 1
112537 1
112658 1
112688 1
112833 1
112941 1
112947 1
113329 1
113335 1
113407 1
113421 1
113460 1
113530 1
113557 1
113578 1
113638 1
113716 1
113797 1
113806 1
113896 1
113936 1
113962 1
114003 1
114043 1
114154 1
114298 1
114410 1
114433 1
114600 1
114613 1
114740 1
114754 1
114780 1
114787 1
114855 1
114867 1
115048 1
115064 1
115091 1
115263 1
115323 1
115635 1
115688 1
115804 1
115808 1
115810 1
115828 1

{1: 4388, 2: 196, 3: 36, 4: 18, 5: 3, 6: 5, 7: 2, 8: 4, 11: 2}

In [18]:
out_file = "data_200.txt"
out_stat_file = './statics_out.txt'


with io.open(out_file, 'w', encoding='utf8') as o:
    for user in user_trajs:
        traj_seq = ['|'.join([c for c in t]) for t
                    in user_trajs[user]]
        if len(traj_seq) > 0:
            for traj in traj_seq:
                o.write(str(user) + '\t' + traj + '\n')
    o.flush()

with io.open(out_stat_file, 'w', encoding='utf8') as o:
    length_dist = dict()
    for user in user_trajs:
        for t in user_trajs[user]:
            length = len(t)
            if length not in length_dist:
                length_dist[length] = 1
            else:
                length_dist[length] += 1
    length_array = sorted(length_dist.items(), key=lambda x:x[0])
    for length,freq in length_array:
        o.write(str(length) + '\t' + str(freq) + '\n')
    o.flush()

In [19]:
len(poi_dict), poi_dict

(9756,
 {'4a5eb95bf964a52019bf1fe3': {'name': 'Lucasfilm Animation Singapore',
   'lat': 1.335005,
   'lon': 103.964682,
   'cat': 'Office'},
  '4a73e804f964a52099dd1fe3': {'name': 'Buddha Tooth Relic Temple & Museum',
   'lat': 1.281391,
   'lon': 103.844348,
   'cat': 'Temple'},
  '4ac7f7f1f964a520e9ba20e3': {'name': 'New Majestic Hotel',
   'lat': 1.279386,
   'lon': 103.840514,
   'cat': 'Hotel'},
  '4ac8148ff964a5208bbb20e3': {'name': 'Sri Mariamman Temple',
   'lat': 1.282644,
   'lon': 103.845286,
   'cat': 'Temple'},
  '4afa194af964a520b71622e3': {'name': 'Clarke Quay Central',
   'lat': 1.28897,
   'lon': 103.846958,
   'cat': 'Mall'},
  '4b05880af964a5208aad22e3': {'name': 'Carlton Hotel',
   'lat': 1.295568,
   'lon': 103.852641,
   'cat': 'Hotel'},
  '4b05880af964a52092ad22e3': {'name': 'Hotel Grand Central',
   'lat': 1.301201,
   'lon': 103.841561,
   'cat': 'Hotel'},
  '4b05880af964a52093ad22e3': {'name': 'Hotel Miramar',
   'lat': 1.288553,
   'lon': 103.837152,
   'cat': 'Hotel'},
  '4b05880af964a52094ad22e3': {'name': 'Hotel Royal',
   'lat': 1.317065,
   'lon': 103.841629,
   'cat': 'Hotel'},
  '4b05880af964a52097ad22e3': {'name': 'Hilton Singapore Orchard',
   'lat': 1.302369,
   'lon': 103.836164,
   'cat': 'Hotel'},
  '4b05880af964a5209aad22e3': {'name': 'Orchard Rendezvous Hotel',
   'lat': 1.306909,
   'lon': 103.827788,
   'cat': 'Hotel'},
  '4b05880af964a5209ead22e3': {'name': 'RELC International Hotel',
   'lat': 1.312886,
   'lon': 103.825948,
   'cat': 'Hotel'},
  '4b05880af964a520a0ad22e3': {'name': 'Quality Hotel Marlow',
   'lat': 1.319991,
   'lon': 103.852526,
   'cat': 'Hotel'},
  '4b05880af964a520a2ad22e3': {'name': 'Bayview Hotel',
   'lat': 1.298523,
   'lon': 103.850138,
   'cat': 'Hotel'},
  '4b05880af964a520a6ad22e3': {'name': 'M Hotel Singapore',
   'lat': 1.273687,
   'lon': 103.845069,
   'cat': 'Hotel'},
  '4b05880af964a520a7ad22e3': {'name': "Copthorne King's Hotel",
   'lat': 1.288628,
   'lon': 103.836572,
   'cat': 'Hotel'},
  '4b05880af964a520a9ad22e3': {'name': 'Peninsula Excelsior Hotel',
   'lat': 1.292064,
   'lon': 103.850172,
   'cat': 'Hotel'},
  '4b05880af964a520acad22e3': {'name': 'InterContinental Singapore',
   'lat': 1.29812,
   'lon': 103.855013,
   'cat': 'Hotel'},
  '4b05880af964a520adad22e3': {'name': 'Novotel Singapore Clarke Quay',
   'lat': 1.291378,
   'lon': 103.845071,
   'cat': 'Hotel'},
  '4b05880af964a520aead22e3': {'name': 'Rendezvous Hotel Singapore',
   'lat': 1.298304,
   'lon': 103.849345,
   'cat': 'Hotel'},
  '4b05880af964a520afad22e3': {'name': 'Paradox Singapore Merchant Court at Clarke Quay',
   'lat': 1.288833,
   'lon': 103.84596,
   'cat': 'Hotel'},
  '4b05880af964a520b0ad22e3': {'name': 'PARKROYAL on Kitchener Road',
   'lat': 1.310644,
   'lon': 103.855766,
   'cat': 'Hotel'},
  '4b05880bf964a52000ae22e3': {'name': 'Que Pasa Wine & Tapas',
   'lat': 1.301838,
   'lon': 103.839098,
   'cat': 'Wine Bar'},
  '4b05880bf964a52004ae22e3': {'name': 'Ice Cold Beer',
   'lat': 1.301884,
   'lon': 103.839104,
   'cat': 'Bar'},
  '4b05880bf964a520b3ad22e3': {'name': 'Gateway Hotel',
   'lat': 1.3147,
   'lon': 103.898146,
   'cat': 'Hotel'},
  '4b05880bf964a520b6ad22e3': {'name': 'Amara Singapore Hotel',
   'lat': 1.274974,
   'lon': 103.843567,
   'cat': 'Hotel'},
  '4b05880bf964a520b7ad22e3': {'name': 'Orchard Hotel Singapore',
   'lat': 1.307516,
   'lon': 103.827931,
   'cat': 'Hotel'},
  '4b05880bf964a520b9ad22e3': {'name': 'Hotel Jen Tanglin Singapore',
   'lat': 1.303835,
   'lon': 103.823831,
   'cat': 'Hotel'},
  '4b05880bf964a520baad22e3': {'name': 'York Hotel',
   'lat': 1.307077,
   'lon': 103.835531,
   'cat': 'Hotel'},
  '4b05880bf964a520bbad22e3': {'name': 'PARKROYAL on Beach Road',
   'lat': 1.300151,
   'lon': 103.860437,
   'cat': 'Hotel'},
  '4b05880bf964a520bfad22e3': {'name': 'Raffles Hotel',
   'lat': 1.294724,
   'lon': 103.853977,
   'cat': 'Hotel'},
  '4b05880bf964a520c0ad22e3': {'name': 'Royal Plaza On Scotts',
   'lat': 1.306766,
   'lon': 103.832345,
   'cat': 'Hotel'},
  '4b05880bf964a520c1ad22e3': {'name': 'Sheraton Towers Singapore',
   'lat': 1.311657,
   'lon': 103.836679,
   'cat': 'Hotel'},
  '4b05880bf964a520c2ad22e3': {'name': 'Singapore Marriott Tang Plaza Hotel',
   'lat': 1.305344,
   'lon': 103.832622,
   'cat': 'Hotel'},
  '4b05880bf964a520c5ad22e3': {'name': 'Pan Pacific Singapore',
   'lat': 1.291986,
   'lon': 103.858971,
   'cat': 'Hotel'},
  '4b05880bf964a520c6ad22e3': {'name': 'The Ritz-Carlton, Millenia Singapore',
   'lat': 1.290806,
   'lon': 103.86009,
   'cat': 'Hotel'},
  '4b05880bf964a520c7ad22e3': {'name': 'Conrad Centennial Singapore',
   'lat': 1.293339,
   'lon': 103.858818,
   'cat': 'Hotel'},
  '4b05880bf964a520c8ad22e3': {'name': 'Swissôtel The Stamford',
   'lat': 1.293223,
   'lon': 103.853411,
   'cat': 'Hotel'},
  '4b05880bf964a520c9ad22e3': {'name': 'Goodwood Park Hotel',
   'lat': 1.30828,
   'lon': 103.83436,
   'cat': 'Hotel'},
  '4b05880bf964a520caad22e3': {'name': 'South East Asia Hotel',
   'lat': 1.301038,
   'lon': 103.853122,
   'cat': 'Hotel'},
  '4b05880bf964a520ccad22e3': {'name': 'Hotel Supreme (原首酒店)',
   'lat': 1.30134,
   'lon': 103.842399,
   'cat': 'Hotel'},
  '4b05880bf964a520cdad22e3': {'name': 'Pasir Panjang Inn',
   'lat': 1.291936,
   'lon': 103.770185,
   'cat': 'Hotel'},
  '4b05880bf964a520cead22e3': {'name': 'Concorde Hotel',
   'lat': 1.30069,
   'lon': 103.842235,
   'cat': 'Hotel'},
  '4b05880bf964a520cfad22e3': {'name': "Shangri-La's Rasa Sentosa Resort & Spa",
   'lat': 1.257147,
   'lon': 103.810029,
   'cat': 'Resort'},
  '4b05880bf964a520d0ad22e3': {'name': 'Four Seasons Hotel Singapore',
   'lat': 1.304642,
   'lon': 103.828568,
   'cat': 'Hotel'},
  '4b05880bf964a520d1ad22e3': {'name': 'Grand Hyatt Singapore',
   'lat': 1.306353,
   'lon': 103.833297,
   'cat': 'Hotel'},
  '4b05880bf964a520d2ad22e3': {'name': 'Grand Copthorne Waterfront Hotel',
   'lat': 1.290497,
   'lon': 103.835232,
   'cat': 'Hotel'},
  '4b05880bf964a520d4ad22e3': {'name': nan,
   'lat': 1.311626,
   'lon': 103.88085,
   'cat': 'Hotel'},
  '4b05880bf964a520daad22e3': {'name': 'Hotel 81 - Palace',
   'lat': 1.311911,
   'lon': 103.880324,
   'cat': 'Hotel'},
  '4b05880bf964a520dead22e3': {'name': 'YMCA International House',
   'lat': 1.297813,
   'lon': 103.847896,
   'cat': 'Hotel'},
  '4b05880bf964a520dfad22e3': {'name': 'YWCA Fort Canning Lodge',
   'lat': 1.297408,
   'lon': 103.845105,
   'cat': 'Hotel'},
  '4b05880bf964a520e4ad22e3': {'name': 'Victoria Hotel',
   'lat': 1.297078,
   'lon': 103.852505,
   'cat': 'Hotel'},
  '4b05880bf964a520e5ad22e3': {'name': 'Costa Sands Resort (Sentosa)',
   'lat': 1.255161,
   'lon': 103.813959,
   'cat': 'Resort'},
  '4b05880bf964a520e6ad22e3': {'name': 'Aranda Country Club',
   'lat': 1.376194,
   'lon': 103.953809,
   'cat': 'Resort'},
  '4b05880bf964a520e7ad22e3': {'name': 'Shangri-La Hotel',
   'lat': 1.311324,
   'lon': 103.826525,
   'cat': 'Hotel'},
  '4b05880bf964a520e8ad22e3': {'name': 'The Fullerton Hotel',
   'lat': 1.286279,
   'lon': 103.852837,
   'cat': 'Hotel'},
  '4b05880bf964a520eaad22e3': {'name': 'The Scarlet',
   'lat': 1.280542,
   'lon': 103.845422,
   'cat': 'Hotel'},
  '4b05880bf964a520ecad22e3': {'name': 'Holiday Inn Singapore Atrium',
   'lat': 1.289045,
   'lon': 103.834615,
   'cat': 'Hotel'},
  '4b05880bf964a520edad22e3': {'name': 'Hotel Royal @ Queens',
   'lat': 1.297813,
   'lon': 103.852176,
   'cat': 'Hotel'},
  '4b05880bf964a520eead22e3': {'name': 'The St. Regis Singapore',
   'lat': 1.305672,
   'lon': 103.825865,
   'cat': 'Hotel'},
  '4b05880bf964a520efad22e3': {'name': 'Siloso Beach Resort',
   'lat': 1.254469,
   'lon': 103.814633,
   'cat': 'Resort'},
  '4b05880bf964a520f1ad22e3': {'name': 'Big O Gaming Cafe',
   'lat': 1.300502,
   'lon': 103.849832,
   'cat': 'Gaming Cafe'},
  '4b05880bf964a520f3ad22e3': {'name': "Bobby's",
   'lat': 1.295087,
   'lon': 103.852086,
   'cat': 'American Restaurant'},
  '4b05880bf964a520f4ad22e3': {'name': 'Brewerkz Restaurant & Microbrewery',
   'lat': 1.289637,
   'lon': 103.844045,
   'cat': 'Gastropub'},
  '4b05880bf964a520faad22e3': {'name': "Molly Malone's Irish Pub",
   'lat': 1.285995,
   'lon': 103.849442,
   'cat': 'Bar'},
  '4b05880bf964a520fbad22e3': {'name': 'Hard Rock Café Singapore',
   'lat': 1.306184,
   'lon': 103.828082,
   'cat': 'Rock Club'},
  '4b05880bf964a520fdad22e3': {'name': 'The Coffee Bean & Tea Leaf',
   'lat': 1.303162,
   'lon': 103.836229,
   'cat': 'Coffee Shop'},
  '4b05880cf964a5200bae22e3': {'name': 'Paulaner Bräuhaus Singapore',
   'lat': 1.29323,
   'lon': 103.858223,
   'cat': 'Brewery'},
  '4b05880cf964a5200dae22e3': {'name': 'The Penny Black Public House',
   'lat': 1.285829,
   'lon': 103.850069,
   'cat': 'Bar'},
  '4b05880cf964a5200eae22e3': {'name': 'Zouk',
   'lat': 1.291117,
   'lon': 103.834866,
   'cat': 'Nightclub'},
  '4b05880cf964a5201cae22e3': {'name': 'Coffee Club',
   'lat': 1.304637,
   'lon': 103.830832,
   'cat': 'Coffee Shop'},
  '4b05880cf964a5201fae22e3': {'name': 'Billy Bombers Classic',
   'lat': 1.299829,
   'lon': 103.855814,
   'cat': 'Diner'},
  '4b05880cf964a52021ae22e3': {'name': 'Crazy Elephant',
   'lat': 1.289926,
   'lon': 103.846378,
   'cat': 'Pub'},
  '4b05880cf964a52027ae22e3': {'name': 'The Living Room',
   'lat': 1.305522,
   'lon': 103.833032,
   'cat': 'Nightclub'},
  '4b05880cf964a5202eae22e3': {'name': 'New Asia',
   'lat': 1.293452,
   'lon': 103.853439,
   'cat': 'Cocktail Bar'},
  '4b05880cf964a52030ae22e3': {'name': 'Attica',
   'lat': 1.28995,
   'lon': 103.84489,
   'cat': 'Nightclub'},
  '4b05880cf964a52033ae22e3': {'name': 'China One',
   'lat': 1.290227,
   'lon': 103.846174,
   'cat': 'Bar'},
  '4b05880cf964a52035ae22e3': {'name': 'Post Bar',
   'lat': 1.286065,
   'lon': 103.85302,
   'cat': 'Cocktail Bar'},
  '4b05880cf964a52039ae22e3': {'name': 'Velvet Underground',
   'lat': 1.291066,
   'lon': 103.835277,
   'cat': 'Nightclub'},
  '4b05880cf964a52046ae22e3': {'name': 'The Pump Room',
   'lat': 1.290484,
   'lon': 103.845327,
   'cat': 'Rock Club'},
  '4b05880df964a5204aae22e3': {'name': "Samy's Curry",
   'lat': 1.306123,
   'lon': 103.811789,
   'cat': 'Indian Restaurant'},
  '4b05880df964a52057ae22e3': {'name': 'Highlander Bar & Restaurant',
   'lat': 1.29042,
   'lon': 103.845466,
   'cat': 'Bar'},
  '4b05880df964a52058ae22e3': {'name': 'Insomnia',
   'lat': 1.295017,
   'lon': 103.852352,
   'cat': 'Cocktail Bar'},
  '4b05880df964a52064ae22e3': {'name': 'Canvas',
   'lat': 1.28942,
   'lon': 103.848955,
   'cat': 'Nightclub'},
  '4b05880df964a5206aae22e3': {'name': 'PLAY Bar & Club',
   'lat': 1.279636,
   'lon': 103.844227,
   'cat': 'Nightclub'},
  '4b05880df964a5206bae22e3': {'name': 'Rupee Room',
   'lat': 1.290869,
   'lon': 103.845726,
   'cat': 'Nightclub'},
  '4b05880df964a5206fae22e3': {'name': 'Helipad',
   'lat': 1.288838,
   'lon': 103.846639,
   'cat': 'Nightclub'},
  '4b05880df964a5207cae22e3': {'name': 'RedDot BrewHouse',
   'lat': 1.306442,
   'lon': 103.811418,
   'cat': 'Bar'},
  '4b05880df964a5207dae22e3': {'name': "Dorothy's Bar",
   'lat': 1.282967,
   'lon': 103.8441,
   'cat': 'Bar'},
  '4b05880df964a52081ae22e3': {'name': 'Eski Bar',
   'lat': 1.285803,
   'lon': 103.849181,
   'cat': 'Bar'},
  '4b05880df964a52087ae22e3': {'name': 'One Rochester',
   'lat': 1.304946,
   'lon': 103.787851,
   'cat': 'Wine Bar'},
  '4b05880df964a5208aae22e3': {'name': 'The White Rabbit',
   'lat': 1.304852,
   'lon': 103.813557,
   'cat': 'French Restaurant'},
  '4b05880ef964a52093ae22e3': {'name': 'Max Brenner Chocolate Bar',
   'lat': 1.289881,
   'lon': 103.856417,
   'cat': 'Dessert Shop'},
  '4b05880ef964a5209fae22e3': {'name': 'Blu Jaz Cafe',
   'lat': 1.300491,
   'lon': 103.858979,
   'cat': 'Jazz Club'},
  '4b05880ef964a520a1ae22e3': {'name': 'Far East Square',
   'lat': 1.283448,
   'lon': 103.848352,
   'cat': 'Mall'},
  '4b05880ef964a520a3ae22e3': {'name': 'Sun Yat Sen Nanyang Memorial Hall 孙中山南洋纪念馆',
   'lat': 1.327946,
   'lon': 103.847137,
   'cat': 'Monument / Landmark'},
  '4b05880ef964a520adae22e3': {'name': "Sir Stamford Raffles Statue (Raffles' Landing Site)",
   'lat': 1.287722,
   'lon': 103.850691,
   'cat': 'Historic Site'},
  '4b05880ef964a520aeae22e3': {'name': 'Supreme Court',
   'lat': 1.290141,
   'lon': 103.850399,
   'cat': 'Courthouse'},
  '4b05880ef964a520b1ae22e3': {'name': 'Holland Village',
   'lat': 1.311085,
   'lon': 103.795248,
   'cat': 'Other Great Outdoors'},
  '4b05880ef964a520b5ae22e3': {'name': 'Jurong Bird Park',
   'lat': 1.320689,
   'lon': 103.706732,
   'cat': 'Zoo'},
  '4b05880ef964a520bbae22e3': {'name': 'Fort Canning Park',
   'lat': 1.295075,
   'lon': 103.846421,
   'cat': 'Park'},
  '4b05880ef964a520c0ae22e3': {'name': 'Chijmes',
   'lat': 1.295128,
   'lon': 103.85214,
   'cat': 'Art Gallery'},
  '4b05880ef964a520d2ae22e3': {'name': 'Kusu Island',
   'lat': 1.223592,
   'lon': 103.86012,
   'cat': 'Island'},
  '4b05880ef964a520d6ae22e3': {'name': 'Clarke Quay',
   'lat': 1.28984,
   'lon': 103.845005,
   'cat': 'Plaza'},
  '4b05880ef964a520d9ae22e3': {'name': "St Joseph's Catholic Church",
   'lat': 1.29841,
   'lon': 103.85315,
   'cat': 'Church'},
  '4b05880ef964a520dcae22e3': {'name': 'Underwater World And Dolphin Lagoon',
   'lat': 1.258584,
   'lon': 103.811424,
   'cat': 'Aquarium'},
  '4b05880ef964a520e4ae22e3': {'name': 'Thian Hock Keng (Temple)',
   'lat': 1.281028,
   'lon': 103.847664,
   'cat': 'Temple'},
  '4b05880ff964a52002af22e3': {'name': 'Singapore Cricket Club',
   'lat': 1.289217,
   'lon': 103.85229,
   'cat': 'Cricket Ground'},
  '4b05880ff964a52008af22e3': {'name': 'Central Fire Station',
   'lat': 1.292293,
   'lon': 103.849419,
   'cat': 'Fire Station'},
  '4b05880ff964a5200daf22e3': {'name': 'Benjamin Sheares Bridge',
   'lat': 1.294002,
   'lon': 103.865379,
   'cat': 'Bridge'},
  '4b05880ff964a52013af22e3': {'name': nan,
   'lat': 1.324675,
   'lon': 103.930172,
   'cat': 'Other Great Outdoors'},
  '4b05880ff964a52023af22e3': {'name': 'Orchard Road Presbyterian Church (ORPC)',
   'lat': 1.297864,
   'lon': 103.847424,
   'cat': 'Church'},
  '4b05880ff964a52024af22e3': {'name': 'Masjid Omar Kampung Melaka (Mosque)',
   'lat': 1.287888,
   'lon': 103.844141,
   'cat': 'Mosque'},
  '4b05880ff964a5202aaf22e3': {'name': 'Kallang River',
   'lat': 1.308976,
   'lon': 103.870175,
   'cat': 'River'},
  '4b05880ff964a5202caf22e3': {'name': 'Malay Heritage Centre',
   'lat': 1.302626,
   'lon': 103.860133,
   'cat': 'Monument / Landmark'},
  '4b05880ff964a520e6ae22e3': {'name': "St Andrew's Cathedral",
   'lat': 1.292694,
   'lon': 103.852161,
   'cat': 'Church'},
  '4b05880ff964a520e7ae22e3': {'name': 'Cathedral Of The Good Shepherd',
   'lat': 1.29619,
   'lon': 103.851228,
   'cat': 'Church'},
  '4b05880ff964a520e8ae22e3': {'name': 'Central Sikh Gurdwara',
   'lat': 1.31863,
   'lon': 103.860681,
   'cat': 'Temple'},
  '4b05880ff964a520ebae22e3': {'name': 'Arab Street',
   'lat': 1.301202,
   'lon': 103.859198,
   'cat': 'Road'},
  '4b05880ff964a520fbae22e3': {'name': 'Masjid Sultan (Mosque)',
   'lat': 1.3021,
   'lon': 103.859162,
   'cat': 'Mosque'},
  '4b05880ff964a520fcae22e3': {'name': '观音堂佛祖庙 Kwan Im Thong Hood Cho Temple',
   'lat': 1.300872,
   'lon': 103.853003,
   'cat': 'Temple'},
  '4b05880ff964a520fdae22e3': {'name': 'Sri Srinivasa Perumal Temple',
   'lat': 1.313239,
   'lon': 103.856315,
   'cat': 'Monument / Landmark'},
  '4b058810f964a52032af22e3': {'name': nan,
   'lat': 1.284283,
   'lon': 103.853807,
   'cat': 'Monument / Landmark'},
  '4b058810f964a52036af22e3': {'name': 'Esplanade Park',
   'lat': 1.289626,
   'lon': 103.853835,
   'cat': 'Park'},
  '4b058810f964a5203caf22e3': {'name': 'Liang Court',
   'lat': 1.291812,
   'lon': 103.845003,
   'cat': 'Mall'},
  '4b058810f964a5203eaf22e3': {'name': 'Singapore River',
   'lat': 1.287995,
   'lon': 103.84943,
   'cat': 'River'},
  '4b058810f964a52040af22e3': {'name': 'Marina Barrage',
   'lat': 1.280519,
   'lon': 103.870518,
   'cat': 'Water Park'},
  '4b058810f964a52048af22e3': {'name': 'Church Of The Sacred Heart',
   'lat': 1.29619,
   'lon': 103.843854,
   'cat': 'Church'},
  '4b058810f964a52049af22e3': {'name': 'Catholic Church of Our Lady of Lourdes',
   'lat': 1.30315,
   'lon': 103.855998,
   'cat': 'Church'},
  '4b058810f964a5204eaf22e3': {'name': 'Merlion Walk',
   'lat': 1.253008,
   'lon': 103.818572,
   'cat': 'Sculpture Garden'},
  '4b058810f964a5204faf22e3': {'name': 'Church of St Teresa',
   'lat': 1.273322,
   'lon': 103.828053,
   'cat': 'Church'},
  '4b058810f964a52050af22e3': {'name': 'Ministry of Digital Development and Information (MDDI)',
   'lat': 1.290835,
   'lon': 103.848377,
   'cat': 'Government Building'},
  '4b058810f964a52052af22e3': {'name': 'Lee Kong Chian Reference Library',
   'lat': 1.297553,
   'lon': 103.854237,
   'cat': 'Library'},
  '4b058810f964a52054af22e3': {'name': 'The Singapore Flyer',
   'lat': 1.289358,
   'lon': 103.863083,
   'cat': 'Scenic Lookout'},
  '4b058810f964a52059af22e3': {'name': 'Rochester Park',
   'lat': 1.305182,
   'lon': 103.787851,
   'cat': 'Neighborhood'},
  '4b058810f964a52061af22e3': {'name': 'LASALLE College of the Arts',
   'lat': 1.302884,
   'lon': 103.851559,
   'cat': 'College Arts Building'},
  '4b058810f964a52063af22e3': {'name': 'National University of Singapore (NUS)',
   'lat': 1.294088,
   'lon': 103.777714,
   'cat': 'University'},
  '4b058810f964a52064af22e3': {'name': 'Dempsey Hill',
   'lat': 1.304426,
   'lon': 103.810059,
   'cat': 'Neighborhood'},
  '4b058810f964a5206baf22e3': {'name': 'Singapore Discovery Centre',
   'lat': 1.331565,
   'lon': 103.678365,
   'cat': 'Museum'},
  '4b058810f964a5206eaf22e3': {'name': "Children's Museum Singapore",
   'lat': 1.292858,
   'lon': 103.849062,
   'cat': 'Museum'},
  '4b058810f964a5206faf22e3': {'name': 'Singapore Art Museum',
   'lat': 1.297189,
   'lon': 103.850908,
   'cat': 'Art Museum'},
  '4b058810f964a52071af22e3': {'name': 'Asian Civilisations Museum',
   'lat': 1.28688,
   'lon': 103.851978,
   'cat': 'History Museum'},
  '4b058810f964a52072af22e3': {'name': 'Changi Prison Museum & Chapel',
   'lat': 1.362289,
   'lon': 103.973907,
   'cat': 'History Museum'},
  '4b058810f964a52078af22e3': {'name': 'Peranakan Museum',
   'lat': 1.294039,
   'lon': 103.849317,
   'cat': 'History Museum'},
  '4b058811f964a52099af22e3': {'name': 'Chinatown Heritage Centre',
   'lat': 1.283441,
   'lon': 103.844267,
   'cat': 'Museum'},
  '4b058811f964a5209aaf22e3': {'name': 'MINT Museum of Toys',
   'lat': 1.296362,
   'lon': 103.854393,
   'cat': 'Museum'},
  '4b058811f964a5209caf22e3': {'name': "Dan Ryan's Chicago Grill",
   'lat': 1.305366,
   'lon': 103.8252,
   'cat': 'American Restaurant'},
  '4b058811f964a5209faf22e3': {'name': "Tony Roma's",
   'lat': 1.29521,
   'lon': 103.858721,
   'cat': 'American Restaurant'},
  '4b058811f964a520a3af22e3': {'name': 'California Pizza Kitchen',
   'lat': 1.306655,
   'lon': 103.828688,
   'cat': 'Pizza Place'},
  '4b058811f964a520a6af22e3': {'name': "Modesto's",
   'lat': 1.306796,
   'lon': 103.828291,
   'cat': 'Italian Restaurant'},
  '4b058811f964a520a9af22e3': {'name': 'Olive Tree Restaurant',
   'lat': 1.298701,
   'lon': 103.854905,
   'cat': 'Mediterranean Restaurant'},
  '4b058812f964a520b2af22e3': {'name': 'Hua Ting Restaurant 華廳',
   'lat': 1.308058,
   'lon': 103.828144,
   'cat': 'Chinese Restaurant'},
  '4b058812f964a520b8af22e3': {'name': 'Man Fu Yuan',
   'lat': 1.298619,
   'lon': 103.854928,
   'cat': 'Chinese Restaurant'},
  '4b058812f964a520d7af22e3': {'name': 'Ma Maison Restaurant',
   'lat': 1.29923,
   'lon': 103.85606,
   'cat': 'Restaurant'},
  '4b058812f964a520d8af22e3': {'name': 'Fish & Co. (The Glass House)',
   'lat': 1.298089,
   'lon': 103.84493,
   'cat': 'Seafood Restaurant'},
  '4b058812f964a520dbaf22e3': {'name': 'Sofra Turkish Cafe & Restaurant',
   'lat': 1.296596,
   'lon': 103.856349,

In [20]:
poi_dict_filter = {}
for user, trajs in user_trajs.items():
    for traj in trajs:
        for r in traj:
            r = r.split(',')
            idx = r[0]
            if idx not in poi_dict_filter:
                poi = poi_dict[idx]
                poi_dict_filter[idx] = {'name': poi['name'], 'lat': poi['lat'], 'lon': poi['lon'], 'cat': poi['cat']}

len(poi_dict_filter)

9756

In [21]:
with open('./poi_traj.txt', 'w', encoding='utf-8') as f:
    for poi_id, data in poi_dict.items():
        line = f"{poi_id}\t{data['name']}\t{data['lat']}\t{data['lon']}\t{data['cat']}\n"
        f.write(line)